import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { legalConfig } from "@/lib/legal/config";

export default function CGVPage() { return <LegalPage title="Conditions générales de vente" eyebrow="Offres payantes" intro="Socle de travail pour les offres payantes de NEXORA. Cette page doit être adaptée aux tarifs, formules, processus de commande et statut juridique réels avant toute commercialisation.">
  <LegalSection title="1. Vendeur et périmètre"><p>Le cocontractant est <strong>{legalConfig.publisherName}</strong>. Les présentes conditions s’appliquent aux offres payantes de NEXORA lorsqu’une commande ou souscription est proposée à un client.</p></LegalSection>
  <LegalSection title="2. Offre et prix"><p>Chaque offre doit présenter avant la commande son prix, sa périodicité, les fonctionnalités incluses, les éventuelles limites d’usage, les taxes applicables et les conditions de renouvellement. Les prix effectivement affichés dans l’interface prévalent sur les valeurs génériques de cette page.</p></LegalSection>
  <LegalSection title="3. Commande et paiement"><p>La commande devient effective selon le parcours de souscription affiché par NEXORA. Le paiement peut être traité par un prestataire de paiement tel que Stripe lorsqu’il est activé. NEXORA ne doit pas stocker les données complètes de carte bancaire si le parcours de paiement n’en a pas besoin.</p></LegalSection>
  <LegalSection title="4. Abonnement et renouvellement"><p>Pour une formule récurrente, la fréquence de facturation, la date de renouvellement et les modalités de résiliation doivent être clairement affichées avant la conclusion du contrat.</p></LegalSection>
  <LegalSection title="5. Droit de rétractation"><p>Lorsqu’un consommateur bénéficie d’un droit de rétractation, les informations et modalités applicables doivent être fournies avant la conclusion du contrat. Si l’exécution d’un service numérique commence immédiatement à la demande du consommateur, le parcours de commande doit recueillir les consentements et informations requis par le droit applicable.</p></LegalSection>
  <LegalSection title="6. Résiliation et remboursement"><p>Les modalités de résiliation, d’arrêt du renouvellement, de remboursement et, le cas échéant, de proratisation doivent être indiquées clairement dans l’offre et dans le parcours de gestion de l’abonnement.</p></LegalSection>
  <LegalSection title="7. Service numérique"><p>NEXORA est fourni comme un service logiciel. Les conditions de disponibilité, maintenance, sécurité, mises à jour et éventuelles limitations doivent être interprétées avec les conditions générales d’utilisation et la documentation du service.</p></LegalSection>
  <LegalSection title="8. Réclamations et médiation"><p>Une réclamation doit d’abord être adressée au service de contact indiqué par NEXORA. Lorsque la médiation de la consommation est applicable, le professionnel doit avoir désigné un médiateur référencé et communiquer ses coordonnées au consommateur : <strong>{legalConfig.mediationName}</strong> — {legalConfig.mediationUrl}.</p></LegalSection>
  <LegalSection title="9. Données personnelles"><p>Les traitements de données personnelles sont décrits dans la <a className="text-primary underline" href="/rgpd">politique de protection des données</a>. Les données nécessaires au paiement peuvent également être traitées par le prestataire de paiement selon son propre cadre de confidentialité.</p></LegalSection>
  <LegalSection title="10. Droit applicable"><p>Le droit applicable et les juridictions compétentes doivent être adaptés au statut de l’éditeur et à la nature du client. Les droits impératifs des consommateurs restent applicables.</p></LegalSection>
</LegalPage>; }
