export type SkillRisk = "read" | "recommendation" | "write" | "critical";
export type SkillCategory = "finance" | "agentic" | "interaction" | "security" | "knowledge";
export type NexoraSkill = { id:string; version:string; name:string; description:string; category:SkillCategory; risk:SkillRisk; tools:readonly string[]; enabled:boolean; requiresHumanApproval:boolean };
const READ = ["get_financial_snapshot","get_budget_status","get_cashflow","get_wealth_snapshot","get_forecast","search_transactions"] as const;
const SKILL_DATA: Array<[string,string,SkillCategory,SkillRisk,readonly string[]]> = [
["finance-budget-analysis","Analyse budgétaire","finance","read",READ],["finance-cashflow","Analyse de trésorerie","finance","read",READ],["finance-spending-anomaly","Détection d'anomalies","finance","read",READ],["finance-recurring-expenses","Dépenses récurrentes","finance","read",READ],["finance-forecast","Contrôle des prévisions","finance","read",READ],["finance-scenario","Simulation de scénarios","finance","recommendation",READ],["finance-savings-capacity","Capacité d'épargne","finance","recommendation",READ],["finance-wealth","Analyse du patrimoine","finance","read",READ],["finance-goal-planning","Planification d'objectif","finance","recommendation",READ],["finance-risk-review","Revue des risques","finance","recommendation",READ],["agent-planning","Décomposition d'objectif","agentic","read",[]],["agent-verification","Vérification des résultats","agentic","read",[]],["agent-source-comparison","Comparaison de sources","agentic","read",["research_web"]],["agent-web-research","Recherche web publique","knowledge","read",["research_web"]],["agent-knowledge-synthesis","Synthèse de connaissances","knowledge","read",["research_web"]],["interaction-page-context","Contexte de page","interaction","read",[]],["interaction-friction","Détection de friction","interaction","read",[]],["security-prompt-injection","Détection de prompt injection","security","read",[]],["security-tool-validation","Validation des outils","security","read",[]],["security-data-isolation","Isolation des données","security","read",[]],["security-write-gate","Contrôle avant écriture","security","critical",["create_recommendation","save_financial_insight"]]
];
export const NEXORA_SKILLS: readonly NexoraSkill[] = SKILL_DATA.map(([id,name,category,risk,tools])=>({id,version:"1.0.0",name,description:name,category,risk,tools,enabled:true,requiresHumanApproval:risk === "write" || risk === "critical"}));
export function listNexoraSkills(options?:{category?:SkillCategory;enabledOnly?:boolean}){return NEXORA_SKILLS.filter(s=>(!options?.category||s.category===options.category)&&(!options?.enabledOnly||s.enabled));}
export function getNexoraSkill(id:string){return NEXORA_SKILLS.find(s=>s.id===id);}
export function skillPrompt(){return listNexoraSkills({enabledOnly:true}).map(s=>`- ${s.id}: ${s.description} [risque=${s.risk}]`).join("\n");}
