import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export default function TermsPage() { return <LegalPage title="Conditions générales d’utilisation" eyebrow="Règles du service" intro="Les présentes conditions encadrent l’utilisation de la version de développement de NEXORA et seront adaptées si le service est ouvert à une commercialisation publique.">
  <LegalSection title="1. Objet"><p>NEXORA fournit un service logiciel destiné à centraliser, visualiser et analyser des informations financières, à suivre des budgets, des transactions, des objectifs et des projections, et à utiliser des fonctionnalités d’intelligence artificielle.</p></LegalSection>
  <LegalSection title="2. Version de développement"><p>La version actuellement accessible est en développement. Certaines fonctionnalités peuvent être expérimentales, évoluer rapidement ou être temporairement indisponibles. Les fonctionnalités de facturation Premium ne sont pas activées dans cette version.</p></LegalSection>
  <LegalSection title="3. Compte et sécurité"><p>L’utilisateur fournit des informations exactes et protège ses moyens d’accès. Il doit signaler toute utilisation non autorisée de son compte. NEXORA peut appliquer des mesures de sécurité, limiter une fonctionnalité ou suspendre temporairement un accès lorsqu’un risque de sécurité ou d’abus est détecté.</p></LegalSection>
  <LegalSection title="4. Données financières"><p>L’utilisateur reste responsable de l’exactitude des informations qu’il saisit ou connecte. Les données bancaires peuvent être retardées, incomplètes ou indisponibles selon l’établissement et le fournisseur d’agrégation. Les projections et analyses sont des estimations et ne constituent pas une garantie de résultat.</p></LegalSection>
  <LegalSection title="5. Intelligence artificielle"><p>Les sorties de LIA sont une aide à l’analyse. Elles peuvent comporter des erreurs ou dépendre de données incomplètes. Une décision financière, fiscale, juridique ou patrimoniale importante doit être vérifiée par l’utilisateur et, lorsque nécessaire, par un professionnel compétent.</p></LegalSection>
  <LegalSection title="6. Actions automatisées et gouvernance"><p>NEXORA distingue les actions de lecture, les recommandations et les actions sensibles. Les actions pouvant modifier un état financier ou présenter un risque important sont soumises aux contrôles de sécurité, au Policy Engine et, lorsque requis, à une validation humaine. L’utilisateur conserve le contrôle des actions sensibles.</p></LegalSection>
  <LegalSection title="7. Open Banking"><p>Les connexions bancaires dépendent de partenaires et de la disponibilité des établissements. L’utilisateur peut révoquer une connexion. Une révocation peut empêcher les synchronisations futures tout en laissant subsister les données historiques lorsque leur conservation reste légitime.</p></LegalSection>
  <LegalSection title="8. Utilisation acceptable"><p>Il est interdit de contourner les mesures de sécurité, d’accéder aux données d’un autre utilisateur, d’extraire massivement les données, de perturber le service, d’utiliser NEXORA pour une activité illicite ou de tenter de faire exécuter à l’IA des actions qui contournent les garde-fous.</p></LegalSection>
  <LegalSection title="9. Disponibilité et évolution"><p>NEXORA peut corriger des erreurs, modifier des fonctionnalités ou interrompre temporairement un service pour maintenance. Les changements importants seront communiqués lorsqu’ils affectent substantiellement l’utilisation du service.</p></LegalSection>
  <LegalSection title="10. Propriété intellectuelle"><p>Les logiciels, interfaces, marques, textes, visuels, bases de données et éléments de NEXORA restent protégés par les droits applicables. Aucun droit de reproduction ou d’exploitation n’est transféré au-delà de ce qui est nécessaire à l’utilisation du service.</p></LegalSection>
  <LegalSection title="11. Résiliation et suppression"><p>L’utilisateur peut demander la fermeture de son compte et l’exercice de ses droits conformément à la politique RGPD. Certaines données peuvent être conservées lorsqu’une obligation légale, une nécessité de sécurité ou une autre base légale le justifie.</p></LegalSection>
  <LegalSection title="12. Droit applicable"><p>Les règles impératives applicables au consommateur ou à l’utilisateur demeurent applicables. Les modalités détaillées de règlement des litiges seront adaptées au statut juridique de l’éditeur avant une ouverture commerciale.</p></LegalSection>
</LegalPage>; }
