import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export default function TermsPage() { return <LegalPage title="Conditions générales d’utilisation" eyebrow="Règles du service" intro="Ces conditions constituent une base de travail pour le fonctionnement de NEXORA. Elles doivent être relues et adaptées par l’éditeur avant publication commerciale.">
  <LegalSection title="1. Objet"><p>NEXORA fournit un service logiciel permettant de centraliser et analyser des informations financières, de construire des budgets et projections et d’utiliser des fonctionnalités d’intelligence artificielle.</p></LegalSection>
  <LegalSection title="2. Compte et sécurité"><p>L’utilisateur fournit des informations exactes et protège ses moyens d’accès. Il doit signaler toute utilisation non autorisée de son compte. NEXORA peut appliquer des mesures de sécurité ou suspendre temporairement un accès en cas de risque.</p></LegalSection>
  <LegalSection title="3. Données financières"><p>L’utilisateur reste responsable de l’exactitude des informations qu’il saisit ou connecte. Une donnée agrégée peut être retardée, incomplète ou indisponible. Les projections sont des estimations et non des garanties.</p></LegalSection>
  <LegalSection title="4. Intelligence artificielle"><p>Les sorties de l’IA sont fournies comme aide à l’analyse. Elles peuvent contenir des erreurs ou dépendre de données incomplètes. L’utilisateur doit vérifier les informations importantes avant toute décision financière, fiscale, juridique ou patrimoniale.</p></LegalSection>
  <LegalSection title="5. Open Banking"><p>Les connexions bancaires dépendent de partenaires et de la disponibilité des établissements concernés. Les consentements et reconnexions sont gérés selon les modalités applicables au service. La révocation d’une connexion peut empêcher les synchronisations futures tout en laissant subsister l’historique déjà importé lorsque la conservation est légitime.</p></LegalSection>
  <LegalSection title="6. Utilisation acceptable"><p>Il est interdit de contourner les mesures de sécurité, d’utiliser le service pour une activité illicite, d’extraire massivement les données, de perturber le service ou de tenter d’accéder aux données d’un autre utilisateur ou espace.</p></LegalSection>
  <LegalSection title="7. Disponibilité et évolution"><p>NEXORA peut évoluer, corriger des erreurs, modifier certaines fonctionnalités ou interrompre temporairement un service pour maintenance. Les engagements contractuels spécifiques, notamment pour une offre payante, devront être précisés dans les conditions commerciales applicables.</p></LegalSection>
  <LegalSection title="8. Responsabilité"><p>Dans les limites autorisées par la loi, NEXORA ne garantit pas l’absence d’erreur, l’exhaustivité permanente des données ni la réalisation d’un résultat financier. Les limitations et exclusions doivent être adaptées au statut de l’éditeur et au droit de la consommation applicable.</p></LegalSection>
  <LegalSection title="9. Résiliation et suppression"><p>Les modalités de fermeture du compte, d’export et de suppression des données doivent être précisées dans la politique de confidentialité et les conditions commerciales applicables.</p></LegalSection>
  <LegalSection title="10. Droit applicable"><p>Le droit applicable et les règles de règlement des litiges doivent être adaptés au statut de l’éditeur et à la situation du client. Les dispositions impératives protectrices du consommateur restent applicables lorsqu’elles le sont.</p></LegalSection>
</LegalPage>; }
