"use client";

import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Bot, Database, Globe2, Power, RefreshCw, ShieldCheck, WalletCards } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import type { LucideIcon } from "lucide-react";

type Controls = { ai_enabled:boolean; web_research_enabled:boolean; banking_refresh_enabled:boolean; cron_autonomy_enabled:boolean; updated_at:string|null };
type Job = { id:string; name:string; action:string; status:string; next_run_at:string|null; last_run_at:string|null; last_status:string|null; last_error:string|null; failure_count:number; admin_disabled:boolean };
type Data = { controls:Controls; metrics:{jobs:number;running:number;errors24h:number;events24h:number}; jobs:Job[] };
type ControlKey = Exclude<keyof Controls,"updated_at">;

const labels:Record<ControlKey,string> = { ai_enabled:"IA LIA globale", web_research_enabled:"Recherche Internet", banking_refresh_enabled:"Rafraîchissement bancaire", cron_autonomy_enabled:"Cron autonomes" };
const icons:Record<ControlKey, LucideIcon> = { ai_enabled:Bot, web_research_enabled:Globe2, banking_refresh_enabled:WalletCards, cron_autonomy_enabled:Activity };
const metricCards:Array<{icon:LucideIcon;label:string;key:keyof Data["metrics"]}> = [
 {icon:Database,label:"Jobs cron",key:"jobs"},{icon:Activity,label:"En cours",key:"running"},{icon:AlertTriangle,label:"Erreurs · 24 h",key:"errors24h"},{icon:ShieldCheck,label:"Événements · 24 h",key:"events24h"}
];

export default function AdminSystemClient(){
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<ControlKey|null>(null); const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin/system",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Système indisponible.");setData(d);}catch(e){setMessage(e instanceof Error?e.message:"Erreur système.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const toggle=async(key:ControlKey,value:boolean)=>{if(key==="ai_enabled"&&!value&&!window.confirm("Couper immédiatement LIA pour tout NEXORA ? Les opérations bancaires existantes ne seront pas supprimées, mais les appels IA et l'autonomie seront bloqués."))return;setBusy(key);setMessage("");try{const r=await fetch("/api/admin/system",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key,value})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Modification refusée.");setData((old)=>old?{...old,controls:d.controls}:old);setMessage(value?`${labels[key]} activé.`:`${labels[key]} désactivé.`);}catch(e){setMessage(e instanceof Error?e.message:"Modification impossible.")}finally{setBusy(null)}};
 return <main className="mx-auto max-w-7xl space-y-6 px-6 py-8">
  <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-semibold text-primary">Administration · Système</p><h1 className="text-3xl font-bold">Système NEXORA</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Centre de contrôle d'urgence et de supervision du runtime. Les coupures globales sont serveur-side, auditées et réversibles.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></div>
  {message&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm">{message}</div>}
  <Card className={data?.controls.ai_enabled===false?"border-destructive/50":"border-emerald-500/30"}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="rounded-xl border p-3"><Power className="h-5 w-5"/></div><div><p className="font-semibold">Kill switch IA global</p><p className="mt-1 text-sm text-muted-foreground">Coupe les capacités LIA et ses exécutions autonomes au niveau serveur. À utiliser immédiatement en cas d'incident.</p></div></div><Button variant={data?.controls.ai_enabled===false?"default":"destructive"} disabled={!data||busy==="ai_enabled"} onClick={()=>void toggle("ai_enabled",data?.controls.ai_enabled===false)}>{data?.controls.ai_enabled===false?"Réactiver LIA":"Désactiver LIA"}</Button></CardContent></Card>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(Object.keys(icons) as ControlKey[]).map((key)=>{const Icon=icons[key];const on=data?.controls[key]!==false;return <Card key={key}><CardContent className="p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{labels[key]}</p><p className="mt-1 font-semibold">{loading?"—":on?"Actif":"Désactivé"}</p><Button className="mt-3 w-full" size="sm" variant="outline" disabled={!data||busy===key} onClick={()=>void toggle(key,!on)}>{on?"Désactiver":"Activer"}</Button></CardContent></Card>})}</div>
  <div className="grid gap-4 md:grid-cols-4">{metricCards.map(({icon:Icon,label,key})=><Card key={key}><CardContent className="p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{data?.metrics[key]??"—"}</p></CardContent></Card>)}</div>
  <Card><CardHeader><CardTitle>Runtime autonome · derniers jobs</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Job</th><th className="p-2">Action</th><th className="p-2">État</th><th className="p-2">Dernière exécution</th><th className="p-2">Prochaine</th><th className="p-2">Échecs</th></tr></thead><tbody>{data?.jobs.map(job=><tr key={job.id} className="border-b last:border-0"><td className="p-2 font-medium">{job.name}</td><td className="p-2">{job.action}</td><td className="p-2">{job.status}{job.admin_disabled?" · admin disabled":""}</td><td className="p-2 text-xs">{job.last_run_at?new Date(job.last_run_at).toLocaleString("fr-FR"):"—"}</td><td className="p-2 text-xs">{job.next_run_at?new Date(job.next_run_at).toLocaleString("fr-FR"):"—"}</td><td className="p-2">{job.failure_count??0}</td></tr>)}</tbody></table>{!data?.jobs.length&&<p className="py-6 text-center text-sm text-muted-foreground">Aucun job enregistré.</p>}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Garde-fous</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm md:grid-cols-2"><div className="rounded-xl border p-4"><p className="font-semibold">Internet en cage</p><p className="mt-1 text-muted-foreground">LIA n'accède pas directement au navigateur de l'administrateur. La recherche passe par un worker serveur limité, HTTPS, timeouts, validation d'URL et filtrage de confiance.</p></div><div className="rounded-xl border p-4"><p className="font-semibold">Finance</p><p className="mt-1 text-muted-foreground">Le rafraîchissement lit les comptes et transactions via les adaptateurs Open Banking. Les actions financières sensibles restent soumises aux politiques et à l'approbation humaine.</p></div></CardContent></Card>
 </main>
}
