import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { PrivacyControls } from "@/components/legal/privacy-controls";

export default function CookiesPage() { return <LegalPage title="Cookies & autres traceurs" eyebrow="Transparence" intro="NEXORA applique le principe de minimisation : les traceurs strictement nécessaires peuvent être utilisés sans consentement lorsqu’ils bénéficient d’une exemption légale ; les traceurs soumis à consentement sont bloqués tant que l’utilisateur n’a pas choisi.">
  <LegalSection title="1. Traceurs strictement nécessaires"><p>Ils servent au fonctionnement du service : authentification et session, sécurité, protection contre les abus, maintien des préférences indispensables et fonctionnement technique. Ils ne sont pas utilisés à des fins publicitaires.</p></LegalSection>
  <LegalSection title="2. Traceur de préférence cookies"><p>NEXORA utilise <code>nexora_cookie_consent</code> pour mémoriser le choix exprimé dans le centre de consentement. Il contient uniquement une préférence technique et une date de choix. Le mécanisme actuel est conservé pour une durée maximale de 6 mois afin d’éviter de redemander le choix à chaque visite.</p></LegalSection>
  <LegalSection title="3. Préférences locales"><p>Le navigateur peut également conserver <code>nexora-privacy-preferences-v1</code> dans le stockage local pour synchroniser l’interface du centre de préférences. Ce stockage ne déclenche aucun service publicitaire ou de suivi.</p></LegalSection>
  <LegalSection title="4. Traceurs optionnels"><p>À la date de cette politique, aucun traceur publicitaire, marketing ou de mesure d’audience non exempté n’est activé. Si un tel service est ajouté, sa finalité, son responsable, sa durée, ses destinataires et son mécanisme de consentement seront documentés avant activation.</p></LegalSection>
  <LegalSection title="5. Votre choix"><p>Vous pouvez accepter, refuser ou personnaliser les traceurs optionnels. Le refus est aussi simple que l’acceptation. Le bouton cookie situé en bas de l’interface reste disponible afin de modifier le choix à tout moment.</p><div className="mt-4 rounded-2xl border bg-card p-4"><PrivacyControls /></div></LegalSection>
  <LegalSection title="6. Principe de consentement"><p>Aucune simple poursuite de navigation ne vaut consentement. Lorsqu’un traceur nécessite un consentement préalable, NEXORA attend une action positive et conserve le choix exprimé pendant la période prévue. Le retrait peut être effectué à tout moment depuis le même mécanisme.</p></LegalSection>
</LegalPage>; }
