"use client";

import { useEffect, useState } from "react";
import { BookOpen, Globe2, Lightbulb, RefreshCw, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type Knowledge = { id:string; title:string; statement:string; authority:string; confidence:number; status:string; tags:string[]|null };
type Skill = { id:string; name:string; slug:string; description:string; category:string; status:string; source_type:string; trust_score:number; use_count:number; success_count:number; failure_count:number };
type Research = { id:string; query:string; minimum_evidence_met:boolean; knowledge_graph_ready:boolean; created_at:string };

type ResearchResponse = {
  results?: any[];
  discovery?: { provider?: string|null; status?: string; errors?: string[] };
  executedSources?: number;
  blocked?: Array<{ url:string; reason:string }>;
  minimumEvidenceMet?: boolean;
};

export default function VeilleAdminClient() {
  const [knowledge,setKnowledge]=useState<Knowledge[]>([]); const [skills,setSkills]=useState<Skill[]>([]); const [research,setResearch]=useState<Research[]>([]);
  const [tab,setTab]=useState<"knowledge"|"research"|"skill">("knowledge"); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [query,setQuery]=useState(""); const [results,setResults]=useState<any[]>([]); const [searching,setSearching]=useState(false); const [researchStatus,setResearchStatus]=useState<string>("");
  const [url,setUrl]=useState(""); const [title,setTitle]=useState(""); const [publisher,setPublisher]=useState(""); const [statement,setStatement]=useState(""); const [authority,setAuthority]=useState("B"); const [tags,setTags]=useState("");
  const [skillName,setSkillName]=useState(""); const [skillDescription,setSkillDescription]=useState(""); const [skillProcedure,setSkillProcedure]=useState(""); const [skillCategory,setSkillCategory]=useState("general"); const [skillExpected,setSkillExpected]=useState(""); const [skillVerification,setSkillVerification]=useState("");

  async function load(){setLoading(true);try{const r=await fetch("/api/admin/veille",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Impossible de charger la veille.");setKnowledge(d.knowledge||[]);setSkills(d.skills||[]);setResearch(d.research||[]);}catch(e){setMessage(e instanceof Error?e.message:"Erreur.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);

  async function searchWeb(){
    const cleanQuery=query.trim();
    if(!cleanQuery)return;
    setSearching(true);setMessage("");setResearchStatus("");setResults([]);
    try{
      // Use the live research pipeline here, not discovery-only. The admin page must
      // exercise the same server-side web cage used by LIA autonomous research.
      const r=await fetch("/api/lia/research/live",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:cleanQuery,maxSources:6,timeoutMs:10000,discover:true})});
      const d=await r.json() as ResearchResponse;
      if(!r.ok)throw new Error((d as any).detail||(d as any).error||"Recherche impossible.");
      setResults(d.results||[]);
      const discovery=d.discovery;
      setResearchStatus(`Moteur: ${discovery?.provider||"aucun"} · statut: ${discovery?.status||"inconnu"} · sources acquises: ${d.executedSources??0} · preuves minimales: ${d.minimumEvidenceMet?"oui":"non"}`);
      if(!(d.results||[]).length)setMessage("Aucune source acquise. Consulte le statut du moteur et les domaines de confiance.");
    }catch(e){setMessage(e instanceof Error?e.message:"Recherche impossible.")}finally{setSearching(false)}
  }
  async function acquire(source:any){try{const r=await fetch("/api/lia/research/acquire",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:source.url})});const d=await r.json();if(!r.ok)throw new Error(d.reason||d.detail||d.error||"Acquisition bloquée.");setUrl(d.finalUrl||d.url||source.url);setTitle(d.title||source.title||"");setPublisher(d.source?.organization||"");setStatement((d.text||"").slice(0,5000));setAuthority(d.trust?.sourceClass==="OFFICIAL"||d.trust?.sourceClass==="AUTHORITY"?"A":d.trust?.sourceClass==="SCIENTIFIC"?"B":"C");setTab("knowledge");setMessage("Source acquise. Vérifie le texte avant de l’enregistrer comme connaissance candidate.");}catch(e){setMessage(e instanceof Error?e.message:"Acquisition impossible.")}}
  async function saveKnowledge(){if(!url.trim()||!title.trim()||!statement.trim()){setMessage("URL, titre et contenu sont requis.");return}setBusy(true);try{const sourceKey=`admin:${new URL(url).hostname}:${btoa(unescape(encodeURIComponent(url))).slice(0,40)}`;const r=await fetch("/api/lia/knowledge/ingest",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source_key:sourceKey,title,publisher,url,statement,authority,confidence:authority==="A"?0.9:0.78,tags:tags.split(",").map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ingestion impossible.");setMessage("Connaissance enregistrée comme candidate. Valide-la ensuite pour qu’elle soit récupérable par LIA.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Ingestion impossible")}finally{setBusy(false)}}
  async function skillCandidate(){if(!skillName.trim()||!skillDescription.trim()||!skillProcedure.trim()){setMessage("Nom, description et procédure sont requis.");return}setBusy(true);try{const r=await fetch("/api/lia/skills",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:skillName,description:skillDescription,procedure:skillProcedure,category:skillCategory,sourceType:"user_provided",expectedResult:skillExpected,verificationSteps:skillVerification.split("\n").map(x=>x.trim()).filter(Boolean).slice(0,10),sourceRefs:url?[url]:[]})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Création du Skill impossible.");setMessage("Skill créé comme candidat. La validation et l’activation restent séparées et gouvernées.");setSkillName("");setSkillDescription("");setSkillProcedure("");setSkillExpected("");setSkillVerification("");await load();}catch(e){setMessage(e instanceof Error?e.message:"Création impossible.")}finally{setBusy(false)}}
  async function action(action:string,id:string){setBusy(true);try{const reason=action==="activate_skill"?window.prompt("Justification d’activation (min. 10 caractères)","Activation après validation humaine, replay sans régression et promotion gouvernée.")||"":"";if(action==="activate_skill"&&reason.trim().length<10){setBusy(false);return}const r=await fetch("/api/admin/veille",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Action impossible.");setMessage(action==="activate_skill"?"Skill activé.":action==="validate_skill"?"Skill validé.":"Connaissance mise à jour.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Action impossible")}finally{setBusy(false)}}

  return <main className="mx-auto max-w-7xl space-y-6 px-6 py-8">
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-semibold text-primary">Administration · LIA</p><h1 className="text-3xl font-bold">Veille & apprentissage</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Espace administrateur pour alimenter LIA avec des sources, articles, connaissances, Skills et procédures candidates. Rien n’est activé silencieusement.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></div>
    {message&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm">{message}</div>}
    <div className="flex flex-wrap gap-2">{([["knowledge","Connaissances",BookOpen],["research","Recherche web",Globe2],["skill","Skills & Loop",Sparkles]] as const).map(([id,label,Icon])=><Button key={id} variant={tab===id?"default":"outline"} onClick={()=>setTab(id)}><Icon className="mr-2 h-4 w-4"/>{label}</Button>)}</div>

    {tab==="research"&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><Search className="h-5 w-5 text-primary"/>Chercher une source fiable</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void searchWeb()}} placeholder="Ex. nouvelles règles RGPD pour les applications financières" className="min-w-0 flex-1 rounded-xl border bg-background px-4 py-3 text-sm"/><Button onClick={()=>void searchWeb()} disabled={searching||!query.trim()}><Search className="mr-2 h-4 w-4"/>{searching?"Recherche…":"Chercher"}</Button></div>{researchStatus&&<div className="rounded-xl border bg-muted/30 p-3 text-xs text-muted-foreground">{researchStatus}</div>}<div className="space-y-2">{results.map((r,index)=><div key={`${r.url||r.title||"result"}-${index}`} className="rounded-xl border p-4"><p className="font-semibold">{r.title||r.claim||"Source"}</p><p className="mt-1 break-all text-xs text-muted-foreground">{r.url||r.source?.url||""}</p>{(r.snippet||r.claim)&&<p className="mt-2 text-xs leading-5 text-muted-foreground">{r.snippet||r.claim}</p>} {r.url&&<Button className="mt-3" size="sm" variant="outline" onClick={()=>void acquire(r)}>Acquérir et analyser</Button>}</div>)}</div>{research.length>0&&<div className="border-t pt-4"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Dernières recherches LIA</p>{research.slice(0,8).map((r,index)=><div key={`${r.id||"research"}-${index}`} className="mt-2 rounded-lg border p-3 text-xs"><b>{r.query}</b><span className="ml-2">{r.minimum_evidence_met?"✓ preuves suffisantes":"⚠ preuves insuffisantes"}</span></div>)}</div>}</CardContent></Card>}

    {tab==="knowledge"&&<div className="grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><Card><CardHeader><CardTitle>Ajouter une connaissance à LIA</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs leading-5 text-muted-foreground">Tu peux partir d’un site ou d’un article, vérifier son contenu, puis l’enregistrer comme connaissance candidate. Une validation explicite est nécessaire avant récupération par défaut.</p><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre / document" className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><input value={publisher} onChange={e=>setPublisher(e.target.value)} placeholder="Éditeur / organisme" className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><textarea value={statement} onChange={e=>setStatement(e.target.value)} placeholder="Extrait ou connaissance à retenir…" className="min-h-40 w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><div className="grid gap-3 sm:grid-cols-2"><select value={authority} onChange={e=>setAuthority(e.target.value)} className="rounded-xl border bg-background px-3 py-2.5 text-sm"><option value="A">A · officiel / autorité</option><option value="B">B · scientifique / recherche</option><option value="C">C · professionnel / fournisseur</option><option value="D">D · secondaire</option><option value="E">E · faible</option></select><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Tags, séparés par des virgules" className="rounded-xl border bg-background px-3 py-2.5 text-sm"/></div><Button onClick={()=>void saveKnowledge()} disabled={busy}><ShieldCheck className="mr-2 h-4 w-4"/>Enregistrer comme connaissance candidate</Button></CardContent></Card><Card><CardHeader><CardTitle>Connaissances récentes</CardTitle></CardHeader><CardContent className="space-y-2">{loading?<p className="text-sm text-muted-foreground">Chargement…</p>:knowledge.slice(0,12).map((k,index)=><div key={`${k.id||k.title}-${index}`} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold">{k.title}</p><p className="mt-1 line-clamp-3 text-xs text-muted-foreground">{k.statement}</p></div><span className="rounded-full border px-2 py-1 text-[10px]">{k.status}</span></div><div className="mt-2 flex flex-wrap gap-2 text-[10px] text-muted-foreground"><span>Autorité {k.authority}</span><span>Confiance {Math.round(Number(k.confidence)*100)}%</span></div>{k.status==="proposed"&&<Button className="mt-3" size="sm" onClick={()=>void action("validate_knowledge",k.id)}>Valider</Button>}</div>)}</CardContent></Card></div>}

    {tab==="skill"&&<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Créer un Skill / Loop candidat</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs leading-5 text-muted-foreground">Donne directement à LIA une méthode : déclencheur, procédure, résultat attendu et vérifications. Le Skill reste candidat jusqu’à validation.</p><input value={skillName} onChange={e=>setSkillName(e.target.value)} placeholder="Nom du Skill" className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><input value={skillCategory} onChange={e=>setSkillCategory(e.target.value)} placeholder="Catégorie" className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><textarea value={skillDescription} onChange={e=>setSkillDescription(e.target.value)} placeholder="Quand LIA doit-elle l’utiliser ?" className="min-h-24 w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><textarea value={skillProcedure} onChange={e=>setSkillProcedure(e.target.value)} placeholder="Étapes de la méthode…" className="min-h-40 w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><input value={skillExpected} onChange={e=>setSkillExpected(e.target.value)} placeholder="Résultat attendu" className="w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><textarea value={skillVerification} onChange={e=>setSkillVerification(e.target.value)} placeholder="Une vérification par ligne" className="min-h-24 w-full rounded-xl border bg-background px-3 py-2.5 text-sm"/><Button onClick={()=>void skillCandidate()} disabled={busy}><Lightbulb className="mr-2 h-4 w-4"/>Créer le candidat</Button></CardContent></Card><Card><CardHeader><CardTitle>Skills & progression</CardTitle></CardHeader><CardContent className="space-y-2">{skills.slice(0,14).map((k,index)=><div key={`${k.id||k.slug}-${index}`} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">{k.name}</p><span className="rounded-full border px-2 py-1 text-[10px]">{k.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{k.description}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] text-muted-foreground"><span>Confiance {k.trust_score}</span><span>Usages {k.use_count}</span><span>Réussites {k.success_count}</span><span>Échecs {k.failure_count}</span></div>{k.status==="candidate"&&<Button className="mt-3" size="sm" variant="outline" onClick={()=>void action("validate_skill",k.id)}>Valider le Skill</Button>}{k.status==="validated"&&<Button className="mt-3 ml-2" size="sm" onClick={()=>void action("activate_skill",k.id)}>Activer</Button>}</div>)}</CardContent></Card></div>}
  </main>;
}
