import { NextResponse } from "next/server";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { nextCronRun } from "@/lib/lia/runtime/cron-scheduler";
import { runProactiveFinancialLoop } from "@/lib/lia/proactive/loop";
import { runFinancialAutopilotObservation, autoClassifyHighConfidence } from "@/lib/lia/financial-autopilot";
import { persistAutopilotSnapshot } from "@/lib/lia/financial-autopilot/persist";
import { syncBankConnection } from "@/lib/banking/sync-engine";
import { getLiaRuntimeControls } from "@/lib/lia/runtime/controls";
import { claimAgentContinuations, finishAgentContinuation } from "@/lib/lia/agentic/continuation";
import { claimAgentMissions, runClaimedMission } from "@/lib/lia/agentic/mission-manager";
import { startAgentLoop } from "@/lib/agents/loop-engine";

export const runtime = "nodejs";
function admin() { const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY; if(!url||!key) throw new Error("Supabase server secret missing."); return createAdminClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}); }
function authorized(request:Request){const configured=process.env.LIA_CRON_SECRET||process.env.CRON_SECRET; if(!configured)return false; return (request.headers.get("authorization")||"")===`Bearer ${configured}`;}
export async function POST(request:Request){
 if(!authorized(request))return NextResponse.json({error:"Cron non autorisé."},{status:401});
 try{
  const supabase=admin(); const now=new Date(); const controls=await getLiaRuntimeControls(supabase);
  if(!controls.cron_autonomy_enabled)return NextResponse.json({now:now.toISOString(),processed:0,paused:true,reason:"admin_global_kill_switch"});
  const {data:jobs,error}=await supabase.from("lia_runtime_jobs").select("id,user_id,name,schedule,status,payload,next_run_at,last_run_at,timezone,failure_count").eq("runtime_type","cron").eq("status","ready").eq("admin_disabled",false).not("schedule","is",null).or(`next_run_at.is.null,next_run_at.lte.${now.toISOString()}`).order("next_run_at",{ascending:true}).limit(20); if(error)throw new Error(error.message); const results:Array<Record<string,unknown>>=[];
  for(const job of jobs??[]){
   const schedule=String(job.schedule||""); let next:Date|null; try{next=nextCronRun(schedule,now,String(job.timezone||"UTC"));}catch{await supabase.from("lia_runtime_jobs").update({status:"blocked",last_status:"invalid_schedule",updated_at:now.toISOString()}).eq("id",job.id).eq("status","ready"); results.push({job_id:job.id,status:"blocked",reason:"invalid_schedule"}); continue;}
   const {data:claimed}=await supabase.from("lia_runtime_jobs").update({status:"running",last_run_at:now.toISOString(),last_status:"running",updated_at:now.toISOString()}).eq("id",job.id).eq("status","ready").select("id,user_id,name,payload,schedule").maybeSingle(); if(!claimed)continue;
   try{
    const action=typeof claimed.payload?.action==="string"?claimed.payload.action:"proactive_financial_watch"; if(!["proactive_financial_watch","goal_watch","autonomous_learning","autonomous_goal_watch","bank_sync"].includes(action))throw new Error("unsupported_cron_action"); let result:any;
    if(action==="autonomous_goal_watch"){const {runAutonomousGoal}=await import("@/lib/lia/autonomous-goal-runner"); const {data:runs,error:runError}=await supabase.from("agent_loop_runs").select("id,status,context").eq("user_id",claimed.user_id).in("status",["running","blocked"]).limit(12); if(runError)throw new Error(runError.message); const active=(runs??[]).filter((run:any)=>!["completed","failed","needs_human"].includes(String(run.context?.goal_lifecycle?.state))); const runResults=[]; for(const run of active.slice(0,4)){try{runResults.push(await runAutonomousGoal(supabase,claimed.user_id,String(run.id),Math.min(8,Number(claimed.payload?.max_steps??8))));}catch(error){runResults.push({loopRunId:run.id,status:"failed",error:error instanceof Error?error.message:"autonomous_goal_failed"});}} result={status:"completed",active_goals:active.length,processed:runResults.length,results:runResults};}
    else if(action==="autonomous_learning"){const {runAutonomousLearningCycle}=await import("@/lib/lia/learning/autonomous"); result=await runAutonomousLearningCycle(supabase,claimed.user_id);}
    else if(action==="bank_sync"){if(!controls.banking_refresh_enabled)result={status:"paused",reason:"banking_refresh_disabled"};else{const {data:connections,error:connectionsError}=await supabase.from("bank_connections").select("id,provider").eq("user_id",claimed.user_id).not("status","in","(revoked,disconnected)");if(connectionsError)throw new Error(connectionsError.message);const syncResults=[];for(const connection of connections??[]){try{const sync=await syncBankConnection({supabase,userId:claimed.user_id,connectionId:String(connection.id)});syncResults.push({connection_id:connection.id,...sync});}catch(error){syncResults.push({connection_id:connection.id,synced:false,error:error instanceof Error?error.message:"bank_sync_failed"});}}result={status:"completed",connections:syncResults.length,synced:syncResults.filter((item:any)=>item.synced).length,results:syncResults};}}
    else if(action==="goal_watch"){const {detectGoalSignals}=await import("@/lib/finance/goal-watch");const {data:goals,error:goalError}=await supabase.from("goals").select("id,name,target_amount,current_amount,target_date,priority").eq("user_id",claimed.user_id).limit(50);if(goalError)throw new Error("goal_watch_context_unavailable");const signals=detectGoalSignals((goals??[]).map(g=>({...g,target_amount:Number(g.target_amount),current_amount:Number(g.current_amount)})));if(!signals.length)result={status:"no_signal"};else{const notifications=signals.map(s=>({user_id:claimed.user_id,type:"system",severity:s.severity,title:s.title,message:s.message,action_href:s.actionHref,dedupe_key:`goal-watch:${s.id}`}));const {error:notifyError}=await supabase.from("notifications").upsert(notifications,{onConflict:"user_id,dedupe_key",ignoreDuplicates:true});if(notifyError)throw new Error("goal_watch_notification_failed");result=await runProactiveFinancialLoop(supabase,claimed.user_id,signals[0].id,{serverMode:true});}}
    else{const snapshot=await runFinancialAutopilotObservation(supabase,claimed.user_id);const persisted=await persistAutopilotSnapshot(supabase,claimed.user_id,snapshot);const {data:prefs}=await supabase.from("lia_autopilot_preferences").select("enabled,auto_classify_transactions,proactive_notifications").eq("user_id",claimed.user_id).maybeSingle();const classification=prefs?.enabled!==false&&prefs?.auto_classify_transactions!==false?await autoClassifyHighConfidence(supabase,claimed.user_id):{applied:0,results:[]};if(prefs?.enabled!==false&&prefs?.proactive_notifications!==false){const notices=snapshot.opportunities.slice(0,8).map(o=>({user_id:claimed.user_id,type:"system",severity:o.severity,title:`LIA · ${o.title}`,message:o.message,action_href:"/pilotage#autopilot",dedupe_key:`autopilot:${o.key}`}));if(notices.length){const {error:noticeError}=await supabase.from("notifications").upsert(notices,{onConflict:"user_id,dedupe_key",ignoreDuplicates:true});if(noticeError)throw new Error("autopilot_notification_failed");}}result={status:"completed",autopilot:{...persisted,classification:classification.applied,observations:snapshot.observations.length,predictions:snapshot.predictions.length}};}
    await supabase.from("lia_runtime_jobs").update({status:"ready",next_run_at:next?.toISOString()??null,last_status:result.status,last_error:null,failure_count:0,updated_at:new Date().toISOString()}).eq("id",job.id);results.push({job_id:job.id,status:"completed",result_status:result.status,next_run_at:next?.toISOString()??null});
   }catch(e){const message=e instanceof Error?e.message:"cron_execution_failed";const failureCount=Math.min(100,Number(job.failure_count??0)+1);await supabase.from("lia_runtime_jobs").update({status:"ready",next_run_at:next?.toISOString()??null,last_status:"failed",last_error:message.slice(0,1000),failure_count:failureCount,updated_at:new Date().toISOString()}).eq("id",job.id);results.push({job_id:job.id,status:"failed",error:message});}
  }
  const missions=await claimAgentMissions(supabase,5); const missionResults=[];
  for(const mission of missions){try{const loopRunId=mission.loop_run_id??await startAgentLoop(supabase,mission.user_id,mission.goal,"cron",{mission_id:mission.id,task:mission.task,parent_id:mission.parent_id}); missionResults.push({id:mission.id,status:(await runClaimedMission({supabase,mission,loopRunId})).status});}catch(error){missionResults.push({id:mission.id,status:"failed",error:error instanceof Error?error.message:"mission_failed"});}}
  const continuations=await claimAgentContinuations(supabase,8); const continuationResults=[];
  for(const continuation of continuations){try{const {runAutonomousGoal}=await import("@/lib/lia/autonomous-goal-runner");const runResult=await runAutonomousGoal(supabase,String(continuation.user_id),String(continuation.loop_run_id),8);const nextState={...((continuation.state as Record<string,unknown>)||{}),last_run:runResult,updated_at:now.toISOString()};const status=runResult.status==="completed"?"completed":runResult.status==="needs_human"?"waiting":runResult.status==="blocked"?"blocked":"waiting";await finishAgentContinuation(supabase,String(continuation.id),status,nextState);continuationResults.push({id:continuation.id,status:runResult.status});}catch(error){const message=error instanceof Error?error.message:"continuation_failed";await finishAgentContinuation(supabase,String(continuation.id),"waiting",{last_error:message,updated_at:now.toISOString()},message);continuationResults.push({id:continuation.id,status:"failed",error:message});}}
  return NextResponse.json({now:now.toISOString(),processed:results.length,results,missions:{claimed:missions.length,processed:missionResults.length,results:missionResults},continuations:{claimed:continuations.length,processed:continuationResults.length,results:continuationResults}});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Cron indisponible."},{status:503});}
}
export async function GET(request:Request){return POST(request);}
