import type { Metadata } from "next";
import Link from "next/link";
import GuidedStart from "@/components/help/guided-start";
import { ArrowRight, BookOpen, Building2, CheckCircle2, CircleHelp, LockKeyhole, MessageCircle, PiggyBank, ShieldCheck, Sparkles, UserRound, WalletCards } from "lucide-react";

export const metadata: Metadata = { title: "Aide & Guide | NEXORA", description: "Guide simple pour apprendre à utiliser NEXORA, pour les particuliers et les entreprises." };

const individual = [
  ["01", "Commencer", "Ouvre ton tableau de bord et regarde simplement les grandes catégories."],
  ["02", "Connecter tes comptes", "Si tu le souhaites, connecte tes comptes bancaires pour utiliser tes données financières autorisées."],
  ["03", "Comprendre", "Regarde tes revenus, tes dépenses, ton solde et tes transactions."],
  ["04", "Faire ton budget", "Fixe des montants simples par catégorie. Le but est de comprendre, pas d'être parfait."],
  ["05", "Tes objectifs", "Choisis un objectif concret : épargne, achat, sécurité financière ou projet."],
  ["06", "Parler à LIA", "Pose une question normale. Aucun vocabulaire financier compliqué n'est nécessaire."],
];
const business = [
  ["01", "Créer l'espace", "L'espace entreprise sert à suivre les finances de l'activité. Le SIRET permet d'identifier l'entreprise."],
  ["02", "Comprendre le tableau", "Commence par le chiffre d'affaires, les encaissements, les charges, les dépenses et la trésorerie."],
  ["03", "Suivre les charges", "Une charge est une dépense liée au fonctionnement de l'entreprise : locaux, logiciels, fournisseurs, services, etc."],
  ["04", "Prévu et réel", "Le prévisionnel indique ce que tu pensais faire. Le réel montre ce qui s'est réellement passé."],
  ["05", "Surveiller la trésorerie", "La trésorerie est l'argent disponible pour faire face aux paiements."],
  ["06", "Utiliser LIA", "Demande une analyse, une explication ou plusieurs options. La décision reste humaine."],
];
const glossary = [
  ["Solde", "L'argent disponible sur un compte à un moment donné."],
  ["Revenu", "L'argent qui entre, par exemple un salaire ou une vente."],
  ["Dépense", "L'argent qui sort pour payer quelque chose."],
  ["Budget", "Le montant que tu prévois pour une catégorie."],
  ["Épargne", "L'argent que tu mets de côté au lieu de le dépenser maintenant."],
  ["Trésorerie", "L'argent disponible pour payer les dépenses d'une entreprise."],
  ["Chiffre d'affaires", "Le total des ventes réalisées par une entreprise sur une période."],
  ["Charge", "Une dépense nécessaire au fonctionnement d'une entreprise."],
  ["Prévision", "Une estimation de ce qui pourrait arriver plus tard."],
  ["Recommandation", "Une proposition expliquée. Ce n'est pas une action exécutée automatiquement."],
];

function Steps({ items }: { items: string[][] }) {
  return <div className="grid gap-3 md:grid-cols-2">{items.map(([n, title, text]) => <article key={n} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-3 flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-xs font-black text-primary">{n}</span><h3 className="font-bold">{title}</h3></div><p className="text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div>;
}

export default function HelpPage() {
  return <main className="mx-auto w-full max-w-6xl px-4 py-6 pb-24 sm:px-6 lg:px-8">
    <section className="overflow-hidden rounded-[2rem] border bg-card shadow-sm"><div className="relative p-6 sm:p-10"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border bg-background/80 px-3 py-1.5 text-xs font-bold text-primary"><BookOpen className="h-4 w-4" /> Guide NEXORA</span><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">Bien utiliser NEXORA, simplement.</h1><p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">Tu n'as pas besoin d'être expert en finance. Comprends d'abord ce qui entre, ce qui sort et ce qui reste, puis avance étape par étape.</p><div className="mt-6 flex flex-wrap gap-2"><a href="#bien-utiliser" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Commencer le guide</a><a href="#particulier" className="rounded-xl border px-4 py-2.5 text-sm font-bold hover:bg-accent">Particulier</a><a href="#entreprise" className="rounded-xl border px-4 py-2.5 text-sm font-bold hover:bg-accent">Entreprise</a></div></div></div><div className="grid border-t sm:grid-cols-3"><div className="flex items-center gap-3 p-5"><CheckCircle2 className="h-5 w-5 text-primary" /><span className="text-sm font-semibold">Simple à comprendre</span></div><div className="flex items-center gap-3 border-t p-5 sm:border-l sm:border-t-0"><ShieldCheck className="h-5 w-5 text-primary" /><span className="text-sm font-semibold">Données gouvernées</span></div><div className="flex items-center gap-3 border-t p-5 sm:border-l sm:border-t-0"><MessageCircle className="h-5 w-5 text-primary" /><span className="text-sm font-semibold">LIA pour t'expliquer</span></div></div></section>

    <nav aria-label="Sommaire du guide" className="sticky top-[4.5rem] z-20 mt-5 overflow-x-auto rounded-2xl border bg-background/90 p-2 shadow-sm backdrop-blur-xl"><div className="flex min-w-max gap-2">{[["#demarrage", "🌱 Premiers pas"],["#bien-utiliser", "🧭 Bien utiliser"], ["#particulier", "👤 Particulier"], ["#entreprise", "🏢 Entreprise"], ["#lia", "🤖 LIA"], ["#securite", "🔐 Sécurité"], ["#lexique", "📖 Lexique"]].map(([href, label]) => <a key={href} href={href} className="rounded-xl px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-accent hover:text-foreground">{label}</a>)}</div></nav>

    <GuidedStart />

    <section id="bien-utiliser" className="scroll-mt-28 py-10"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Le plus important</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">🧭 La méthode NEXORA en 5 étapes</h2><p className="mt-3 text-muted-foreground">Si tu ne sais pas par où commencer, suis cet ordre.</p></div><div className="grid gap-4 lg:grid-cols-5">{[["1", "Je regarde", "Mes comptes, mes revenus et mes dépenses."],["2", "Je comprends", "Où part mon argent et ce qui change."],["3", "Je m'organise", "Je crée un budget et des objectifs."],["4", "Je prévois", "Je regarde ce qui pourrait arriver."],["5", "Je décide", "Je choisis quoi faire avec les informations."]].map(([n,t,x]) => <article key={n} className="rounded-2xl border bg-card p-5 shadow-sm"><span className="text-2xl font-black text-primary">{n}</span><h3 className="mt-3 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{x}</p></article>)}</div><div className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-5 text-sm leading-6"><strong>💡 Règle simple :</strong> ne cherche pas à tout remplir dès le premier jour. Comprends d'abord ta situation, puis améliore-la petit à petit.</div></section>

    <section id="particulier" className="scroll-mt-28 py-10"><div className="mb-6 flex items-start gap-4"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><UserRound className="h-6 w-6" /></span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Notice utilisateur</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">👤 NEXORA pour les particuliers</h2><p className="mt-2 text-muted-foreground">Pour gérer ton argent personnel sans avoir besoin de connaître la finance.</p></div></div><Steps items={individual} /><details className="mt-4 rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-bold">Ma première semaine avec NEXORA</summary><div className="mt-4 grid gap-3 text-sm text-muted-foreground sm:grid-cols-2"><p><strong>Jour 1 :</strong> regarde ton tableau de bord.</p><p><strong>Jour 2 :</strong> regarde tes transactions et les grosses dépenses.</p><p><strong>Jour 3 :</strong> regarde ton budget et ajuste ce qui ne correspond pas à ta réalité.</p><p><strong>Jour 4 :</strong> définis un objectif simple.</p><p><strong>Jour 5 :</strong> demande à LIA de t'expliquer un point.</p><p><strong>Jour 6-7 :</strong> regarde les alertes et les prévisions.</p></div></details></section>

    <section id="entreprise" className="scroll-mt-28 py-10"><div className="mb-6 flex items-start gap-4"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Building2 className="h-6 w-6" /></span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Notice utilisateur</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">🏢 NEXORA pour les entreprises</h2><p className="mt-2 text-muted-foreground">Pour comprendre les revenus, les charges, le budget et la trésorerie de l'activité.</p></div></div><Steps items={business} /><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><WalletCards className="h-5 w-5 text-primary" /><h3 className="mt-3 font-bold">CA ≠ trésorerie</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Une entreprise peut vendre beaucoup et avoir peu d'argent disponible à un instant donné.</p></div><div className="rounded-2xl border bg-card p-5"><PiggyBank className="h-5 w-5 text-primary" /><h3 className="mt-3 font-bold">Prévu ≠ réel</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Le budget est une prévision. Les transactions montrent ce qui s'est réellement passé.</p></div><div className="rounded-2xl border bg-card p-5"><CircleHelp className="h-5 w-5 text-primary" /><h3 className="mt-3 font-bold">Un doute ?</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Si un chiffre semble étrange, vérifie la donnée ou demande à LIA de l'expliquer.</p></div></div></section>

    <section id="lia" className="scroll-mt-28 py-10"><div className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Sparkles className="h-6 w-6" /></span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Guide LIA</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">🤖 Comment parler à LIA</h2><p className="mt-2 text-muted-foreground">Parle-lui comme à quelqu'un qui t'aide à comprendre tes finances.</p></div></div><div className="mt-7 grid gap-4 md:grid-cols-3">{[["QUESTION SIMPLE", "« Est-ce que je dépense trop ? »", "Commence par une question normale."],["QUESTION PRÉCISE", "« Pourquoi mon budget est dépassé ? »", "Une question précise aide LIA à mieux cibler l'analyse."],["QUESTION ACTIONNABLE", "« Donne-moi 3 façons de réduire mes dépenses. »", "LIA peut présenter plusieurs options et leurs conséquences possibles."]].map(([a,b,c]) => <div key={a} className="rounded-2xl border p-5"><p className="text-xs font-black text-muted-foreground">{a}</p><p className="mt-3 font-semibold">{b}</p><p className="mt-2 text-sm text-muted-foreground">{c}</p></div>)}</div><div className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-5 text-sm leading-6"><strong>🧠 À retenir :</strong> LIA peut analyser, expliquer, prévoir et recommander. <strong>Elle ne décide pas à ta place.</strong> Une recommandation reste une proposition à examiner.</div><Link href="/lia" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Parler à LIA <ArrowRight className="h-4 w-4" /></Link></div></section>

    <section id="securite" className="scroll-mt-28 py-10"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-card p-6"><LockKeyhole className="h-6 w-6 text-primary" /><h2 className="mt-4 text-xl font-black">🔐 Sécurité</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Ne partage jamais ton mot de passe. Vérifie les informations importantes et signale toute donnée incorrecte. NEXORA sépare les données utiles à l'IA des informations qui doivent rester côté serveur.</p></div><div className="rounded-2xl border bg-card p-6"><CircleHelp className="h-6 w-6 text-primary" /><h2 className="mt-4 text-xl font-black">⚠️ Une information semble fausse ?</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Ne prends pas une décision financière importante sur un chiffre que tu n'as pas vérifié. Vérifie la source, la transaction ou le compte concerné.</p></div></div></section>

    <section id="lexique" className="scroll-mt-28 py-10"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Mini dictionnaire</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">📖 Les mots financiers, en français simple</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{glossary.map(([term, definition]) => <div key={term} className="rounded-2xl border bg-card p-4"><p className="font-bold">{term}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{definition}</p></div>)}</div></section>

    <section className="rounded-[2rem] border bg-card p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-black">Tu es perdu ? Commence ici. 👋</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Ouvre le tableau de bord, regarde tes informations principales, puis avance une étape à la fois.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Ouvrir mon tableau de bord <ArrowRight className="h-4 w-4" /></Link><Link href="/faq" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold hover:bg-accent">Voir la FAQ <CircleHelp className="h-4 w-4" /></Link></div></section>
  </main>;
}
