"use client";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type Health = { skillId:string; slug:string; name:string; trustScore:number; activeVersionId:string; health:{status:string;sampleSize:number;successes:number;failures:number;failureRate:number;recentFailures:number;rollbackRecommended:boolean;automaticRollbackAllowed:boolean;reasons:string[]}; };
type Item = { id:string; title:string; category:string; verdict:string; baseline_score:number; candidate_score:number; score_delta:number; regressions:string[]; status:string; created_at:string };
type Correlation = { reports:Array<{skillId:string;skillVersionId:string;activatedAt:string|null;previousVersionId:string|null;current:{sampleSize:number;averageQualityScore:number;correctionRate:number;blockedRate:number};previous:{sampleSize:number;averageQualityScore:number;correctionRate:number;blockedRate:number}|null;deltas:{qualityScore:number|null;correctionRate:number|null;blockedRate:number|null};signal:string;confidence:string}>; };
type Telemetry = { summary:{sampleSize:number;averageQualityScore:number|null;correctionRate:number|null;blockedRate:number|null;recommendationCount:number;recommendationRate:number|null;recommendationAverageQuality:number|null}; };
export default function LearningReviewClient(){
 const [items,setItems]=useState<Item[]>([]); const [health,setHealth]=useState<Health[]>([]); const [telemetry,setTelemetry]=useState<Telemetry|null>(null); const [correlation,setCorrelation]=useState<Correlation|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){setLoading(true);const [r,h,t,c]=await Promise.all([fetch("/api/admin/lia/learning-review",{cache:"no-store"}),fetch("/api/admin/lia/activation-health",{cache:"no-store"}),fetch("/api/admin/lia/production-telemetry",{cache:"no-store"}),fetch("/api/admin/lia/production-correlation",{cache:"no-store"})]);const j=await r.json();const hj=await h.json();const tj=await t.json(); const cj=await c.json();if(!r.ok)setError(j.error||"Erreur");else setItems(j.items||[]);if(h.ok)setHealth(hj.items||[]);if(t.ok)setTelemetry(tj); if(c.ok)setCorrelation(cj); setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function promote(id:string){const r=await fetch("/api/admin/lia/learning-promotion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reviewId:id})});const j=await r.json();if(!r.ok){setError(j.error||"Promotion impossible");return}setItems(x=>x.map(i=>i.id===id?{...i,status:j.status||i.status}:i))}
 async function decide(id:string,decision:"approve"|"reject"|"request_replay"){const note=decision==="approve"?"Approuvé pour l'étape suivante de gouvernance humaine.":decision==="reject"?"Rejeté lors de la revue humaine.":"Replay supplémentaire demandé avant décision.";const r=await fetch("/api/admin/lia/learning-review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,decision,note})});const j=await r.json();if(!r.ok){setError(j.error||"Erreur de mise à jour");return}setItems(x=>x.map(i=>i.id===id?{...i,...j.item}:i))}
 return <Card><CardHeader><CardTitle>Télémétrie de qualité en production</CardTitle></CardHeader><CardContent className="pt-0"><p className="mb-4 text-xs text-muted-foreground">Mesure agrégée sur 30 jours des réponses produites par les Skills actives. Aucune donnée brute n’est exposée et ces métriques ne déclenchent aucune promotion, activation ou rollback automatique.</p>{telemetry?<div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><span className="rounded-xl border p-3 text-sm">Observations <b>{telemetry.summary.sampleSize}</b></span><span className="rounded-xl border p-3 text-sm">Qualité moy. <b>{telemetry.summary.averageQualityScore ?? "—"}%</b></span><span className="rounded-xl border p-3 text-sm">Corrigées <b>{telemetry.summary.correctionRate ?? "—"}%</b></span><span className="rounded-xl border p-3 text-sm">Bloquées <b>{telemetry.summary.blockedRate ?? "—"}%</b></span><span className="rounded-xl border p-3 text-sm">Recommandations <b>{telemetry.summary.recommendationCount}</b></span><span className="rounded-xl border p-3 text-sm">Qualité reco. <b>{telemetry.summary.recommendationAverageQuality ?? "—"}%</b></span></div>:<p className="text-sm text-muted-foreground">Aucune télémétrie disponible.</p>}</CardContent>
<CardHeader><CardTitle>Corrélation production · versions actives</CardTitle></CardHeader><CardContent className="pt-0"><p className="mb-4 text-xs text-muted-foreground">Comparaison observationnelle entre une version activée et sa version précédente. Ce signal n’établit pas une causalité et ne déclenche aucun apprentissage, rollback ou activation automatique.</p>{!correlation?.reports.length?<p className="text-sm text-muted-foreground">Pas assez de données versionnées pour établir une comparaison.</p>:<div className="grid gap-3 md:grid-cols-2">{correlation.reports.map(r=><div key={`${r.skillId}-${r.skillVersionId}`} className="rounded-xl border p-4"><div className="flex items-center justify-between"><b>Version {r.skillVersionId.slice(0,8)}</b><span className="rounded-full border px-2 py-1 text-xs">{r.signal}</span></div><p className="mt-1 text-xs text-muted-foreground">Confiance {r.confidence} · {r.current.sampleSize} observations</p>{r.previous?<div className="mt-3 grid grid-cols-3 gap-2 text-sm"><span>Qualité <b>{r.deltas.qualityScore!>0?`+${r.deltas.qualityScore}`:r.deltas.qualityScore} pts</b></span><span>Corrigées <b>{r.deltas.correctionRate!>0?`+${r.deltas.correctionRate}`:r.deltas.correctionRate} pts</b></span><span>Bloquées <b>{r.deltas.blockedRate!>0?`+${r.deltas.blockedRate}`:r.deltas.blockedRate} pts</b></span></div>:<p className="mt-3 text-xs text-muted-foreground">Aucune baseline précédente exploitable.</p>}</div>)}</div>}</CardContent>
<CardHeader><CardTitle>Post-activation · santé des Skills</CardTitle></CardHeader><CardContent className="pt-0"><p className="mb-4 text-xs text-muted-foreground">Observation des succès/échecs sur 30 jours. Une alerte critique recommande une revue/rollback humain ; aucun rollback automatique n’est autorisé.</p>{health.length===0?<p className="text-sm text-muted-foreground">Aucune Skill active observée.</p>:<div className="grid gap-3 md:grid-cols-2">{health.map(h=><div key={h.skillId} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><b>{h.name}</b><p className="text-xs text-muted-foreground">v active · {h.health.sampleSize} observations</p></div><span className="rounded-full border px-2 py-1 text-xs">{h.health.status}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><span>Succès <b>{h.health.successes}</b></span><span>Échecs <b>{h.health.failures}</b></span><span>Taux échec <b>{h.health.failureRate}%</b></span></div>{h.health.rollbackRecommended&&<p className="mt-3 text-xs text-destructive">Revue humaine / rollback recommandé — jamais automatique.</p>}</div>)}</div>}</CardContent>
<CardHeader><CardTitle>Candidats d'apprentissage</CardTitle></CardHeader><CardContent>{error&&<p className="mb-4 rounded-lg border p-3 text-sm text-destructive">{error}</p>}{loading?<p className="text-sm text-muted-foreground">Chargement…</p>:!items.length?<p className="text-sm text-muted-foreground">Aucun candidat dans la file.</p>:<div className="space-y-3">{items.map(i=><div key={i.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{i.title}</b><p className="text-xs text-muted-foreground">{i.category} · verdict {i.verdict} · {new Date(i.created_at).toLocaleString("fr-FR")}</p></div><span className="rounded-full border px-2 py-1 text-xs">{i.status}</span></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><span>Baseline <b>{i.baseline_score}%</b></span><span>Candidat <b>{i.candidate_score}%</b></span><span>Delta <b>{i.score_delta>0?`+${i.score_delta}`:i.score_delta} pts</b></span></div>{Array.isArray(i.regressions)&&i.regressions.length>0&&<p className="mt-3 text-xs text-destructive">Régressions : {i.regressions.join(", ")}</p>}{i.status==="pending"&&<div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={()=>decide(i.id,"approve")}>Approuver</Button><Button size="sm" variant="outline" onClick={()=>decide(i.id,"request_replay")}>Demander un replay</Button><Button size="sm" variant="destructive" onClick={()=>decide(i.id,"reject")}>Rejeter</Button></div>}{i.status==="approved"&&<div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={()=>promote(i.id)}>Promouvoir vers validated</Button><span className="self-center text-xs text-muted-foreground">Activation séparée et bloquée</span></div>}</div>)}</div>}</CardContent></Card>
}
