"use client";

import { FinancialCrossDomainSummary } from "@/components/finance/financial-cross-domain-summary";
import { useEffect, useMemo, useState } from "react";
import { Ban, CheckCircle2, Clock3, ExternalLink, RefreshCw, ShieldCheck, LockKeyhole, WalletCards, ArrowDownRight, ArrowUpRight, TrendingUp, Search, Landmark } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Account={id:string;connection_id:string;name:string;account_type:string;iban_masked:string|null;currency:string;balance:number|null;available_balance:number|null;last_synced_at:string|null;provider:string;status?:"active"|"disabled"|"revoked"};
type Tx={id:string;account_id:string;booked_at:string;description:string;merchant_name:string|null;amount:number;currency:string;category:string|null;pending:boolean};
type Connection={id:string;provider:string;status:string;institution_name:string|null;institution_logo_url:string|null;last_synced_at:string|null;consent_expires_at:string|null;reconnect_due_at:string|null};
type HistoryPoint={date:string;eur:number;currencies:Record<string,number>};
type AvailableAccount={id:string;name:string;type:string;currency:string;balance:number|null;disabled:boolean;ibanMasked:string|null};

const money=(value:number,currency="EUR")=>new Intl.NumberFormat("fr-FR",{style:"currency",currency}).format(value);

function BalanceChart({points}:{points:HistoryPoint[]}){
  const width=720,height=220,pad=28;
  const values=points.map(p=>p.eur); const max=Math.max(...values,0); const min=Math.min(...values,0); const range=Math.max(max-min,1);
  const coords=points.map((p,i)=>({x:pad+(i/Math.max(points.length-1,1))*(width-pad*2),y:height-pad-((p.eur-min)/range)*(height-pad*2)}));
  const line=coords.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ");
  return <div className="space-y-2"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{money(max)}</span><span>EUR · {points.length} point(s)</span></div><svg viewBox={`0 0 ${width} ${height}`} className="h-52 w-full overflow-visible" role="img" aria-label="Évolution du solde en euros"><path d={line} fill="none" stroke="currentColor" strokeWidth="3" className="text-primary" strokeLinecap="round" strokeLinejoin="round"/><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad} stroke="currentColor" className="text-border"/><circle cx={coords.at(-1)?.x} cy={coords.at(-1)?.y} r="5" className="fill-primary"/></svg><div className="flex justify-between text-xs text-muted-foreground"><span>{points[0]?.date ? new Date(points[0].date).toLocaleDateString("fr-FR"):""}</span><span>{points.at(-1)?.date ? new Date(points.at(-1)!.date).toLocaleDateString("fr-FR"):""}</span></div></div>;
}

export default function BanquePage(){
 const [accounts,setAccounts]=useState<Account[]>([]); const [transactions,setTransactions]=useState<Tx[]>([]); const [connections,setConnections]=useState<Connection[]>([]); const [availableAccounts,setAvailableAccounts]=useState<Record<string,AvailableAccount[]>>({}); const [totals,setTotals]=useState<Record<string,number>>({}); const [available,setAvailable]=useState<Record<string,number>>({}); const [flow,setFlow]=useState({income:0,expenses:0,net:0}); const [providers,setProviders]=useState<string[]>([]); const [history,setHistory]=useState<HistoryPoint[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string|null>(null); const [query,setQuery]=useState("");
 const load=async()=>{setBusy(true);setNotice(null);try{const [o,c,h]=await Promise.all([fetch("/api/banking/overview",{cache:"no-store"}),fetch("/api/banking/connections",{cache:"no-store"}),fetch("/api/banking/history?days=90",{cache:"no-store"})]);const od=await o.json();const cd=await c.json();const hd=await h.json();if(!o.ok)throw new Error(od.error??"Vue financière indisponible.");if(!c.ok)throw new Error(cd.error??"Connexions indisponibles.");if(!h.ok)throw new Error(hd.error??"Historique indisponible.");const connectionRows=cd.connections??[];const availability=await Promise.all(connectionRows.filter((c:Connection)=>c.status!=="revoked"&&c.status!=="disconnected").map(async(c:Connection)=>{try{const r=await fetch(`/api/banking/accounts?connectionId=${encodeURIComponent(c.id)}`,{cache:"no-store"});const d=await r.json();return [c.id,(r.ok?d.accounts??[]:[])] as const;}catch{return [c.id,[]] as const;}}));setAvailableAccounts(Object.fromEntries(availability));setAccounts(od.accounts??[]);setTransactions(od.transactions??[]);setConnections(connectionRows);setTotals(od.totalsByCurrency??{});setAvailable(od.availableByCurrency??{});setFlow(od.recentFlow??{income:0,expenses:0,net:0});setProviders(cd.providers??[]);setHistory(hd.points??[]);}catch(e){setNotice(e instanceof Error?e.message:"Impossible de charger les comptes.");}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const totalEur=totals.EUR??0; const availableEur=available.EUR??0; const activeConnections=connections.filter(c=>c.status==="active").length;
 const accountNames=useMemo(()=>Object.fromEntries(accounts.map(a=>[a.id,a.name])),[accounts]);
 const filteredTransactions=useMemo(()=>{const q=query.trim().toLowerCase();return q?transactions.filter(t=>[t.merchant_name,t.description,t.category,accountNames[t.account_id]].filter(Boolean).join(" ").toLowerCase().includes(q)):transactions;},[transactions,query,accountNames]);
 const connect=async()=>{const provider=providers[0];if(!provider){setNotice("Aucun fournisseur Open Banking n'est activé.");return;}const r=await fetch("/api/banking/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider})});const d=await r.json();if(r.ok&&d.authorizationUrl)window.location.assign(d.authorizationUrl);else setNotice(d.error??"Connexion bancaire impossible.");};
 const syncAll=async()=>{setBusy(true);setNotice(null);try{for(const c of connections.filter(c=>c.status!=="revoked"&&c.status!=="disconnected")){await fetch("/api/banking/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:c.id})});}await load();}finally{setBusy(false);}};
 const manage=async(c:Connection,mode:"reconnect"|"manage")=>{setBusy(true);setNotice(null);try{const r=await fetch("/api/banking/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:c.provider,connectionId:c.id,mode})});const d=await r.json();if(r.ok&&d.authorizationUrl)window.location.assign(d.authorizationUrl);else setNotice(d.error??"Opération bancaire impossible.");}finally{setBusy(false);}};
 const revoke=async(c:Connection)=>{setBusy(true);try{await fetch(`/api/banking/connections?id=${encodeURIComponent(c.id)}`,{method:"DELETE"});await load();}finally{setBusy(false);}};
 const activateAll=async(c:Connection)=>{const ids=(availableAccounts[c.id]??[]).filter(a=>a.disabled).map(a=>a.id);if(!ids.length){setNotice("Aucun compte supplémentaire à activer.");return;}setBusy(true);setNotice(null);try{const r=await fetch("/api/banking/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:c.id,accountIds:ids})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Activation des comptes impossible.");setNotice(`✓ ${d.activated??ids.length} compte(s) bancaire(s) activé(s).`);await fetch("/api/banking/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:c.id})});await load();}catch(e){setNotice(e instanceof Error?e.message:"Activation impossible.");}finally{setBusy(false);}};
 const revokeAccount=async(a:Account)=>{setBusy(true);setNotice(null);try{const r=await fetch(`/api/banking/accounts?connectionId=${encodeURIComponent(a.connection_id)}&accountId=${encodeURIComponent(a.id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error??"Révocation du compte impossible.");setNotice("✓ Accès Open Banking au compte révoqué.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Révocation impossible.");}finally{setBusy(false);}};
 return <main className="mx-auto max-w-7xl space-y-6 px-6 py-8">
  <FinancialCrossDomainSummary />
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Open Banking · Financial Cockpit</p><h1 className="text-3xl font-bold">Mes finances</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Une vue centrale de tes comptes, de tes liquidités et de tes opérations. Les données restent en lecture seule et alimentent ensuite le modèle financier de NEXORA.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void syncAll()} disabled={busy||connections.length===0}><RefreshCw className={`mr-2 h-4 w-4 ${busy?"animate-spin":""}`}/>Synchroniser</Button><Button onClick={()=>void connect()} disabled={busy||providers.length===0}><ExternalLink className="mr-2 h-4 w-4"/>Ajouter une banque</Button></div></div>
  <Card className="border-primary/20"><CardContent className="flex gap-4 p-5"><ShieldCheck className="mt-1 h-6 w-6 text-primary"/><div><p className="font-semibold">Connexion bancaire sécurisée</p><p className="mt-1 text-sm text-muted-foreground">NEXORA ne demande pas tes identifiants bancaires. Le consentement passe par le fournisseur Open Banking puis ta banque.</p></div></CardContent></Card>
  <div className="grid gap-4 md:grid-cols-4"><Card><CardHeader><CardTitle className="text-sm">Liquidités EUR</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{money(totalEur)}</p><p className="mt-1 text-xs text-muted-foreground">Solde agrégé</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Disponible EUR</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{money(availableEur)}</p><p className="mt-1 text-xs text-muted-foreground">Capacité disponible déclarée</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Flux entrants</CardTitle></CardHeader><CardContent><p className="flex items-center gap-2 text-2xl font-bold"><ArrowUpRight className="h-5 w-5"/>{money(flow.income)}</p><p className="mt-1 text-xs text-muted-foreground">Sur les 50 opérations récentes</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Flux sortants</CardTitle></CardHeader><CardContent><p className="flex items-center gap-2 text-2xl font-bold"><ArrowDownRight className="h-5 w-5"/>{money(flow.expenses)}</p><p className="mt-1 text-xs text-muted-foreground">En EUR</p></CardContent></Card></div>
  <div className="grid gap-6 lg:grid-cols-[1.5fr_.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5"/>Évolution de la liquidité</CardTitle></CardHeader><CardContent>{history.length>1?<BalanceChart points={history}/>:<div className="flex h-52 items-center justify-center text-sm text-muted-foreground">Synchronise tes comptes plusieurs fois pour construire l'historique.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5"/>Répartition des comptes</CardTitle></CardHeader><CardContent className="space-y-3">{accounts.length?accounts.map(a=><div key={a.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{a.name}</p><p className="text-xs text-muted-foreground">{a.account_type} · {a.currency}</p></div><b className="shrink-0 text-sm">{a.balance==null?"—":money(Number(a.balance),a.currency||"EUR")}</b></div>):<p className="text-sm text-muted-foreground">Aucun compte connecté.</p>}</CardContent></Card></div>
  <Card><CardHeader className="flex flex-row items-center justify-between gap-3"><div><CardTitle>Comptes bancaires</CardTitle><p className="mt-1 text-xs text-muted-foreground">{accounts.length} compte(s) · {activeConnections} connexion(s) active(s)</p></div></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{accounts.length?accounts.map(a=><div key={a.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><WalletCards className="h-5 w-5"/><p className="font-semibold">{a.name}</p></div><p className="mt-1 text-xs text-muted-foreground">{a.account_type} · {a.currency}{a.iban_masked?` · ${a.iban_masked}`:""}</p></div><div className="text-right"><p className="text-xl font-bold">{a.balance==null?"—":money(Number(a.balance),a.currency||"EUR")}</p><p className="text-xs text-muted-foreground">Disponible : {a.available_balance==null?"—":money(Number(a.available_balance),a.currency||"EUR")}</p></div></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Synchronisé : {a.last_synced_at?new Date(a.last_synced_at).toLocaleString("fr-FR"):"jamais"}</p>{a.status!=="revoked"&&<Button variant="ghost" size="sm" disabled={busy||a.status==="disabled"} onClick={()=>void revokeAccount(a)}><Ban className="mr-2 h-4 w-4"/>Révoquer l'accès</Button>}</div></div>):<div className="rounded-xl border border-dashed p-8 text-center md:col-span-2"><WalletCards className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-medium">Aucun compte connecté</p><p className="mt-1 text-sm text-muted-foreground">Connecte ta première banque pour faire apparaître tes comptes et tes soldes ici.</p></div>}</CardContent></Card>
  <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Opérations</CardTitle><p className="mt-1 text-xs text-muted-foreground">Les 50 dernières opérations synchronisées</p></div><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une opération…"/></div></div></CardHeader><CardContent>{filteredTransactions.length?<div className="divide-y">{filteredTransactions.map(t=><div key={t.id} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate font-medium">{t.merchant_name||t.description}</p><p className="text-xs text-muted-foreground">{accountNames[t.account_id]??"Compte"} · {new Date(t.booked_at).toLocaleDateString("fr-FR")}{t.category?` · ${t.category}`:""}</p></div><p className={`shrink-0 font-semibold ${Number(t.amount)>=0?"":"text-destructive"}`}>{Number(t.amount)>=0?"+":""}{money(Number(t.amount),t.currency||"EUR")}</p></div>)}</div>:<p className="py-8 text-center text-sm text-muted-foreground">{query?"Aucune opération ne correspond à ta recherche.":"Aucune opération synchronisée."}</p>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Connexions bancaires</CardTitle><p className="mt-1 text-xs text-muted-foreground">Les comptes découverts par Powens peuvent nécessiter une activation volontaire avant synchronisation.</p></CardHeader><CardContent className="space-y-3">{connections.length?connections.map(c=><div key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{c.institution_name??"Établissement bancaire"}</p><p className="text-xs text-muted-foreground">Fournisseur : {c.provider}</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-muted px-3 py-1 text-xs font-medium">{c.status==="active"?<CheckCircle2 className="h-3.5 w-3.5"/>:<Clock3 className="h-3.5 w-3.5"/>}{c.status}</span></div><div className="mt-3 text-xs text-muted-foreground">Dernière synchronisation : {c.last_synced_at?new Date(c.last_synced_at).toLocaleString("fr-FR"):"jamais"}</div>{c.reconnect_due_at&&c.status!=="revoked"&&<div className={`mt-2 text-xs font-medium ${new Date(c.reconnect_due_at).getTime()<=Date.now()?"text-destructive":"text-muted-foreground"}`}>{new Date(c.reconnect_due_at).getTime()<=Date.now()?"Reconnexion requise maintenant":"Reconnexion requise avant le "+new Date(c.reconnect_due_at).toLocaleDateString("fr-FR")}</div>}{c.status!=="revoked"&&<div className="mt-3 flex flex-wrap gap-2">{c.status!=="active"&&<Button variant="outline" disabled={busy} onClick={()=>void manage(c,"reconnect")}><RefreshCw className="mr-2 h-4 w-4"/>Réparer la connexion</Button>}<Button variant="outline" disabled={busy} onClick={()=>void manage(c,"manage")}><ExternalLink className="mr-2 h-4 w-4"/>Gérer les comptes</Button>{(availableAccounts[c.id]??[]).filter(a=>a.disabled).length>0&&<Button variant="outline" disabled={busy} onClick={()=>void activateAll(c)}>Activer {(availableAccounts[c.id]??[]).filter(a=>a.disabled).length} compte(s)</Button>}<Button variant="outline" disabled={busy} onClick={()=>void revoke(c)}><Ban className="mr-2 h-4 w-4"/>Révoquer</Button></div>}</div>):<p className="text-sm text-muted-foreground">Aucune connexion bancaire.</p>}</CardContent></Card>
  <div className="flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground"><LockKeyhole className="h-4 w-4"/><span>Les identifiants bancaires et les payloads bruts des fournisseurs ne sont jamais exposés à cette interface.</span></div>
  {notice&&<p className="text-xs text-muted-foreground">{notice}</p>}
 </main>;
}
