-- Gérer Finance v4.31 — In-app notifications.
-- Notifications are user-scoped, auditable and safe to dismiss. Financial
-- decisions are never made by the LLM: these records are generated by SQL rules.

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('new_transaction','saving_opportunity','budget_alert','forecast_alert','system')),
  severity text not null default 'info' check (severity in ('info','success','warning','danger')),
  title text not null,
  message text not null,
  action_href text,
  dedupe_key text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, read_at) where read_at is null;
create unique index if not exists notifications_user_dedupe_idx on public.notifications(user_id, dedupe_key) where dedupe_key is not null;

alter table public.notifications enable row level security;
drop policy if exists notifications_select_own on public.notifications;
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_select_own on public.notifications for select using (auth.uid() = user_id);
create policy notifications_update_own on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
revoke insert, delete on public.notifications from anon, authenticated;
revoke all on public.notifications from anon;

-- Enable realtime updates for the in-app bell when the publication is available.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
exception when insufficient_privilege then
  null;
end $$;

-- A new expense creates a lightweight notification. No financial recommendation
-- is made here; it simply tells the user that a new fact entered the ledger.
create or replace function public.notify_new_transaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.amount < 0 then
    insert into public.notifications(user_id, type, severity, title, message, action_href, dedupe_key)
    values (
      NEW.user_id,
      'new_transaction',
      'info',
      'Nouvelle dépense',
      format('%s · %s €', left(NEW.label, 80), to_char(abs(NEW.amount), 'FM999999990D00')),
      '/transactions',
      'tx:' || NEW.id::text
    )
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  end if;
  return NEW;
end;
$$;
revoke execute on function public.notify_new_transaction() from public, anon, authenticated;
drop trigger if exists transaction_notification on public.transactions;
create trigger transaction_notification after insert on public.transactions for each row execute procedure public.notify_new_transaction();

-- Refresh deterministic notifications for the current month. The caller may
-- only refresh their own notification set.
create or replace function public.refresh_financial_notifications(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  month_start date := date_trunc('month', current_date)::date;
  next_month date := (date_trunc('month', current_date) + interval '1 month')::date;
  scenario jsonb;
  safety numeric := 0;
  income numeric := 0;
  planned numeric := 0;
  spent numeric := 0;
  balance numeric := 0;
  actual_income numeric := 0;
  actual_expense numeric := 0;
  net numeric := 0;
  elapsed numeric := greatest(least(extract(day from current_date) / extract(day from (date_trunc('month', current_date) + interval '1 month - 1 day')), 1), 0);
  inserted_count integer := 0;
begin
  if uid is null or uid <> p_user_id then
    raise exception 'notification_refresh_forbidden' using errcode = '42501';
  end if;

  select envelopes, safety_reserve, income into scenario, safety, income
  from public.budget_scenarios
  where user_id = uid and period_start = month_start
  limit 1;

  select coalesce(sum(balance),0) into balance from public.accounts where user_id = uid;
  select coalesce(sum(amount) filter (where amount > 0),0), coalesce(sum(abs(amount)) filter (where amount < 0),0)
    into actual_income, actual_expense
  from public.transactions
  where user_id = uid and occurred_at >= month_start and occurred_at < next_month;
  net := actual_income - actual_expense;

  if scenario is not null then
    select coalesce(sum(greatest(coalesce((value->>'planned')::numeric,0),0)),0),
           coalesce(sum(greatest(coalesce((value->>'spent')::numeric,0),0)),0)
      into planned, spent
    from jsonb_array_elements(case when jsonb_typeof(scenario->'envelopes') = 'array' then scenario->'envelopes' else '[]'::jsonb end);
  end if;

  -- Savings opportunity: only when there is a positive current-month net and
  -- the available balance is above the configured safety reserve.
  if net > 0 and balance > safety and net >= 50 then
    insert into public.notifications(user_id, type, severity, title, message, action_href, dedupe_key)
    values (uid, 'saving_opportunity', 'success', 'Il est temps d’épargner',
      format('Ton mois est actuellement positif de %s €. Une partie peut être mise de côté tout en gardant ta réserve de sécurité.', to_char(net, 'FM999999990D00')),
      '/previsions', 'saving:' || month_start::text)
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
    inserted_count := inserted_count + 1;
  end if;

  -- Global envelope pace alert. The budget page remains the detailed source.
  if planned > 0 and elapsed > 0 and spent / planned - elapsed >= 0.15 then
    insert into public.notifications(user_id, type, severity, title, message, action_href, dedupe_key)
    values (uid, 'budget_alert', case when spent / planned - elapsed >= 0.30 then 'danger' else 'warning' end,
      'Budget à surveiller',
      format('%s %% du budget des enveloppes est consommé pour environ %s %% du mois écoulé.', round((spent/planned)*100), round(elapsed*100)),
      '/budget', 'pace:' || month_start::text)
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
    inserted_count := inserted_count + 1;
  end if;

  -- Forecast warning when the actual month is already negative.
  if net < 0 then
    insert into public.notifications(user_id, type, severity, title, message, action_href, dedupe_key)
    values (uid, 'forecast_alert', 'warning', 'Mois actuellement déficitaire',
      format('Les dépenses dépassent les revenus de %s € sur le mois en cours.', to_char(abs(net), 'FM999999990D00')),
      '/previsions', 'negative:' || month_start::text)
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
    inserted_count := inserted_count + 1;
  end if;

  return inserted_count;
end;
$$;
revoke execute on function public.refresh_financial_notifications(uuid) from public, anon;
grant execute on function public.refresh_financial_notifications(uuid) to authenticated;

comment on table public.notifications is 'User-scoped in-app notifications generated by deterministic application rules.';
