-- NEXORA V5.08.30 — Admin Open Banking + entreprise de démonstration.
-- Le SIRET ci-dessous est fictif et réservé à la démonstration administrateur.
DO $$
DECLARE v_user_id uuid; v_workspace_id uuid; v_connection_id uuid; v_account_id uuid;
BEGIN
  SELECT id INTO v_user_id FROM auth.users WHERE lower(email)='flo.billard02200@gmail.com' LIMIT 1;
  IF v_user_id IS NULL THEN RETURN; END IF;
  SELECT id INTO v_workspace_id FROM public.financial_workspaces WHERE owner_user_id=v_user_id AND name='NEXORA Entreprise — Démo' LIMIT 1;
  IF v_workspace_id IS NULL THEN INSERT INTO public.financial_workspaces(owner_user_id,workspace_type,name,status) VALUES(v_user_id,'business','NEXORA Entreprise — Démo','active') RETURNING id INTO v_workspace_id; END IF;
  INSERT INTO public.financial_workspace_members(workspace_id,user_id,role,status) VALUES(v_workspace_id,v_user_id,'owner','active') ON CONFLICT(workspace_id,user_id) DO UPDATE SET role='owner',status='active';
  INSERT INTO public.business_profiles(workspace_id,legal_name,trade_name,siret,siren,legal_form,activity_label,city,country_code,verification_status,verification_source,verified_at,sirene_snapshot) VALUES(v_workspace_id,'NEXORA Entreprise — Démo','NEXORA Demo','00000000000000','000000000','Société de démonstration','Données de démonstration','Paris','FR','verified','nexora-admin-demo',now(),jsonb_build_object('demo',true,'warning','SIRET fictif réservé à la démonstration administrateur')) ON CONFLICT(workspace_id) DO UPDATE SET verification_status='verified',verification_source='nexora-admin-demo',sirene_snapshot=excluded.sirene_snapshot,updated_at=now();
  IF NOT EXISTS(SELECT 1 FROM public.bank_connections WHERE user_id=v_user_id AND provider='demo' AND workspace_id=v_workspace_id AND external_connection_id='nexora-demo-connection') THEN INSERT INTO public.bank_connections(user_id,provider,status,institution_name,external_connection_id,last_synced_at,next_sync_at,consent_expires_at,consent_granted_at,reconnect_due_at,workspace_id,metadata) VALUES(v_user_id,'demo','active','Banque Démo NEXORA','nexora-demo-connection',now(),now()+interval '24 hours',now()+interval '90 days',now(),now()+interval '90 days',v_workspace_id,jsonb_build_object('demo',true)); END IF;
  SELECT id INTO v_connection_id FROM public.bank_connections WHERE user_id=v_user_id AND provider='demo' AND workspace_id=v_workspace_id AND external_connection_id='nexora-demo-connection' LIMIT 1;
  SELECT id INTO v_account_id FROM public.bank_accounts WHERE connection_id=v_connection_id AND external_account_id='nexora-demo-account' LIMIT 1;
  IF v_account_id IS NULL THEN INSERT INTO public.bank_accounts(user_id,connection_id,provider,external_account_id,name,account_type,iban_masked,currency,balance,available_balance,last_synced_at,status,workspace_id,metadata) VALUES(v_user_id,v_connection_id,'demo','nexora-demo-account','Compte courant — Démo','checking','FR76 •••• •••• •••• 0000','EUR',12450,12100,now(),'active',v_workspace_id,jsonb_build_object('demo',true)) RETURNING id INTO v_account_id; END IF;
  INSERT INTO public.bank_transactions(user_id,account_id,connection_id,provider,external_transaction_id,booked_at,description,merchant_name,amount,currency,category,pending,metadata) VALUES(v_user_id,v_account_id,v_connection_id,'demo','demo-income-1',current_date-4,'Encaissement client démo','Client Démo',4200,'EUR','Revenus',false,jsonb_build_object('demo',true)),(v_user_id,v_account_id,v_connection_id,'demo','demo-expense-1',current_date-3,'Abonnement logiciel démo','SaaS Démo',-189,'EUR','Abonnements',false,jsonb_build_object('demo',true)),(v_user_id,v_account_id,v_connection_id,'demo','demo-expense-2',current_date-1,'Fournisseur démo','Fournisseur Démo',-740,'EUR','Fournisseurs',false,jsonb_build_object('demo',true)) ON CONFLICT(connection_id,external_transaction_id) DO NOTHING;
END $$;
