"use client";
import { useEffect, useState } from "react";
import { Activity, Bot, CalendarClock, CircleStop, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const icons: Record<string, any> = { agent: Bot, stop: CircleStop, curator: Sparkles, cron: CalendarClock };
const labels: Record<string,string> = { agent:"Agent", stop:"Stop", curator:"Curator", cron:"Cron" };

export default function RuntimePage(){
 const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/lia/runtime",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Runtime indisponible.");setData(d)}catch(e){setError(e instanceof Error?e.message:"Erreur inattendue.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 return <main className="mx-auto w-full max-w-6xl px-4 py-6 pb-28 sm:px-6">
  <section className="rounded-3xl border bg-gradient-to-br from-primary/10 via-background to-background p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-primary/15 p-3"><ShieldCheck className="h-7 w-7 text-primary"/></div><div><Badge>Runtime LIA</Badge><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">LIA orchestre son propre runtime</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Les types Agent, Stop, Curator et Cron structurent l'exécution. Les tâches planifiées sont désormais créées, ajustées ou mises en pause automatiquement par LIA selon l'utilisation de l'application.</p></div></div></section>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(labels).map(([key,label])=>{const I=icons[key];const d=data?.descriptors?.[key];return <Card key={key} className="p-5"><I className="h-5 w-5 text-primary"/><div className="mt-3 flex items-center justify-between gap-2"><h2 className="font-semibold">{label}</h2><Badge variant="outline">{data?.counts?.[key]??0}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{d?.purpose}</p><div className="mt-4 flex flex-wrap gap-2"><Badge variant="secondary">Policy Gate</Badge>{d?.requiresHumanApproval&&<Badge variant="outline">Validation</Badge>}</div></Card>})}</div>
  <Card className="mt-5 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Pilotage automatique</p><h2 className="mt-1 text-xl font-bold">LIA observe → décide de la cadence → exécute</h2></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></div><div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-2xl border p-4"><b>Observation</b><p className="mt-1 text-xs text-muted-foreground">LIA observe l’activité, les objectifs et le contexte autorisé.</p></div><div className="rounded-2xl border p-4"><b>Cadence</b><p className="mt-1 text-xs text-muted-foreground">La fréquence s’adapte à l’usage et aux besoins observés.</p></div><div className="rounded-2xl border p-4"><b>Exécution</b><p className="mt-1 text-xs text-muted-foreground">Le runtime natif planifie, réclame et journalise les exécutions.</p></div><div className="rounded-2xl border p-4"><b>Apprentissage</b><p className="mt-1 text-xs text-muted-foreground">Les cycles réussis, échecs et événements deviennent des signaux pour ajuster la suite.</p></div></div></Card>
  <Card className="mt-5 border-primary/20 bg-primary/5 p-5 sm:p-6"><div className="flex items-start gap-3"><Activity className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><div><p className="font-semibold">Progression du runtime</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Cette page devient un journal vivant : chaque création, réveil, réussite, échec, adaptation de cadence ou apprentissage doit apparaître dans les événements. LIA ne reçoit jamais ici une permission financière.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border bg-background/70 p-3 text-xs"><b>{data?.jobs?.length ?? 0}</b><span className="ml-1 text-muted-foreground">jobs suivis</span></div><div className="rounded-xl border bg-background/70 p-3 text-xs"><b>{data?.events?.length ?? 0}</b><span className="ml-1 text-muted-foreground">événements récents</span></div><div className="rounded-xl border bg-background/70 p-3 text-xs"><b>{(data?.events ?? []).filter((e:any)=>String(e.status)==='completed').length}</b><span className="ml-1 text-muted-foreground">événements réussis</span></div></div></div></div></Card>
  {error&&<Card className="mt-5 border-destructive/30 p-5 text-sm text-destructive">{error}</Card>}
  <Card className="mt-5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Derniers événements</p>{loading&&!data?<p className="mt-3 text-sm text-muted-foreground">Chargement…</p>:<div className="mt-4 space-y-2">{(data?.events??[]).slice(0,12).map((e:any)=><div key={e.id} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border p-3 text-sm"><div><Badge variant="outline">{e.runtime_type}</Badge><span className="ml-2 font-medium">{e.event}</span></div><span className="text-xs text-muted-foreground">{new Date(e.created_at).toLocaleString("fr-FR")}</span></div>)}</div>}</Card>
 </main>
}
