import type { SupabaseClient } from "@supabase/supabase-js";

export type SkillHit = { skill_id:string; slug:string; name:string; description:string; category:string; status:"validated"|"active"; trust_score:number; version:number; content:string };
export async function searchLiaSkills(supabase:SupabaseClient,userId:string,query:string,category?:string,limit=8):Promise<SkillHit[]>{const{data,error}=await supabase.rpc("lia_search_skills",{p_user_id:userId,p_query:query.slice(0,300),p_category:category??null,p_limit:Math.min(Math.max(limit,1),20)});if(error)throw new Error(`Skill registry indisponible : ${error.message}`);return(data??[])as SkillHit[];}
const normalize=(value:string)=>value.toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
function objectiveExpansion(objective:string){const s=normalize(objective);const terms=new Set<string>();if(/(budget|depense|enveloppe|epargne|mois|fin de mois|mensuel)/.test(s))["budget","dépenses","épargne","cashflow","prévision","écarts"].forEach(x=>terms.add(x));if(/(solde|compte|tresorerie|cashflow|flux|revenu|finance)/.test(s))["finance","cashflow","analyse","liquidité"].forEach(x=>terms.add(x));if(/(risque|anomal|derive|alerte|probleme|danger)/.test(s))["risque","anomalie","dépenses","vérification"].forEach(x=>terms.add(x));if(/(prevision|projection|avenir|trajectoire|simulation|simule|achat|decision)/.test(s))["prévision","scénario","sensibilité","risque"].forEach(x=>terms.add(x));if(/(cherche|recherche|source|internet|actualite|reglement|veille)/.test(s))["recherche","vérification","source","connaissance"].forEach(x=>terms.add(x));return[...terms];}
/** Bounded multi-skill selection. Full-catalog retrieval avoids conjunctive FTS returning zero for natural objectives. */
export async function selectRelevantLiaSkills(supabase:SupabaseClient,userId:string,objective:string,options:{category?:string;limit?:number;minimum?:number}={}):Promise<SkillHit[]>{const limit=Math.min(Math.max(options.limit??8,1),12);const cleanObjective=objective.trim().slice(0,1000);const expandedTerms=objectiveExpansion(cleanObjective);const batches=await Promise.all([searchLiaSkills(supabase,userId,"",options.category,20).catch(()=>[]),searchLiaSkills(supabase,userId,cleanObjective,options.category,12).catch(()=>[]),...expandedTerms.slice(0,2).map(q=>searchLiaSkills(supabase,userId,q,options.category,12).catch(()=>[]))]);const candidates=new Map<string,SkillHit>();for(const batch of batches)for(const skill of batch)candidates.set(skill.skill_id,skill);const objectiveTokens=new Set(normalize(`${cleanObjective} ${expandedTerms.join(" ")}`).split(/\s+/).filter(t=>t.length>=4));const scored=[...candidates.values()].map(skill=>{const skillTokens=new Set(normalize(`${skill.name} ${skill.description} ${skill.category} ${skill.content}`).split(/\s+/).filter(t=>t.length>=4));let overlap=0;for(const token of objectiveTokens)if(skillTokens.has(token))overlap++;const baseline=skill.slug==="financial-agent-intelligence"?0.5:0;const trust=Math.max(0,Math.min(1,Number(skill.trust_score||0)/100));return{skill,score:overlap*2+trust*0.25+baseline};}).sort((a,b)=>b.score-a.score);const selected=scored.slice(0,limit).map(e=>e.skill);const minimum=Math.min(Math.max(options.minimum??2,1),limit);if(selected.length<minimum){const baseline=[...candidates.values()].find(s=>s.slug==="financial-agent-intelligence");if(baseline&&!selected.some(s=>s.skill_id===baseline.skill_id))selected.push(baseline);}return selected.slice(0,limit);}
export function buildSkillCandidate(input:{name:string;description:string;procedure:string;triggerContext:Record<string,unknown>;expectedResult?:string;verificationSteps?:string[];failureModes?:string[];sourceRefs?:string[];correction?:string}){const content=[`# ${input.name}`,"","## When to Use",input.description,"","## Procedure",input.procedure,input.correction?`\n## Correction\n${input.correction}`:"","","## Verification",...(input.verificationSteps??["Vérifier le résultat attendu avant réutilisation."]),"","## Pitfalls",...(input.failureModes??["Ne jamais contourner les politiques d'autorisation."])].join("\n");return{name:input.name.slice(0,120),description:input.description.slice(0,500),content,triggerContext:input.triggerContext,expectedResult:input.expectedResult??null,verificationSteps:input.verificationSteps??[],failureModes:input.failureModes??[],sourceRefs:input.sourceRefs??[],memoryGate:{useful:true,reliable:false,reproducible:false,generalizable:false,obsolete:false,evidence_required:true}};}
