import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { legalConfig } from "@/lib/legal/config";

export default function RGPDPage() { return <LegalPage title="Protection des données & RGPD" eyebrow="Vie privée" intro="Cette page explique les principes de traitement des données de NEXORA. Elle doit être finalisée avec les informations juridiques réelles de l’éditeur et les traitements effectivement déployés.">
  <LegalSection title="Responsable du traitement"><p>Le responsable du traitement est <strong>{legalConfig.publisherName}</strong>, {legalConfig.legalForm}, dont le siège est situé {legalConfig.address}. Contact données personnelles : <strong>{legalConfig.privacyEmail}</strong>. {legalConfig.dpoEmail.startsWith("[") ? "Un DPO n’est indiqué ici que s’il est effectivement désigné." : `Point de contact DPO : ${legalConfig.dpoEmail}.`}</p></LegalSection>
  <LegalSection title="Données susceptibles d’être traitées"><p>Selon les fonctionnalités utilisées : identité et coordonnées de compte, données d’authentification, données de profil, informations financières saisies manuellement, transactions, comptes et soldes issus d’une connexion bancaire, informations de budget et d’objectifs, données nécessaires au support, journaux techniques et données nécessaires à la sécurité.</p></LegalSection>
  <LegalSection title="Finalités et bases juridiques"><ul className="list-disc space-y-2 pl-5"><li>Fourniture du service et exécution du contrat : création de compte, fonctionnalités financières, sécurité du service.</li><li>Respect d’obligations légales lorsqu’elles existent.</li><li>Intérêt légitime : sécurité, prévention des abus, amélioration technique et continuité du service, dans les limites du droit applicable.</li><li>Consentement : traitements qui l’exigent, notamment certains traceurs optionnels ou communications commerciales.</li></ul></LegalSection>
  <LegalSection title="Données bancaires et Open Banking"><p>Lorsqu’une connexion bancaire est activée, NEXORA peut recevoir des données de comptes et de transactions par l’intermédiaire d’un fournisseur d’agrégation. NEXORA ne demande pas à l’utilisateur de communiquer ses identifiants bancaires dans l’interface NEXORA lorsque le parcours du fournisseur prévoit une authentification auprès de la banque. Les données et autorisations dépendent du fournisseur, de la banque et du consentement donné par l’utilisateur.</p></LegalSection>
  <LegalSection title="IA et décisions automatisées"><p>NEXORA peut utiliser des traitements d’IA pour analyser les informations fournies et générer des explications, prévisions, recommandations ou propositions. Les traitements ne doivent pas être présentés comme infaillibles. Lorsque le droit impose une information spécifique sur un profilage ou une décision automatisée produisant des effets juridiques ou similaires, les modalités correspondantes devront être précisées avant le déploiement du traitement concerné.</p></LegalSection>
  <LegalSection title="Destinataires et sous-traitants"><p>Les données peuvent être traitées par NEXORA et ses prestataires techniques nécessaires au fonctionnement du service, notamment hébergement, base de données, authentification, agrégation bancaire, paiement et services d’IA lorsque ces services sont activés. La liste opérationnelle des prestataires, leurs rôles, leurs pays de traitement et les garanties de transfert doivent être maintenus à jour dans la version publiée de cette politique.</p></LegalSection>
  <LegalSection title="Conservation"><p>Les durées de conservation doivent être définies par catégorie de données selon leur finalité, les obligations légales et les besoins de sécurité. NEXORA doit appliquer une politique de suppression ou d’anonymisation cohérente avec ces durées.</p></LegalSection>
  <LegalSection title="Vos droits"><p>Selon les conditions prévues par le RGPD : accès, rectification, effacement, limitation, opposition, portabilité lorsque applicable et retrait du consentement lorsque le traitement repose sur celui-ci. Pour exercer vos droits : <strong>{legalConfig.privacyEmail}</strong>. Vous pouvez également introduire une réclamation auprès de la CNIL.</p></LegalSection>
  <LegalSection title="Sécurité et violation de données"><p>NEXORA applique des mesures techniques et organisationnelles destinées à protéger les données. En cas de violation de données personnelles, une procédure interne doit permettre d’évaluer le risque et, lorsque les conditions légales sont réunies, de notifier l’autorité compétente et les personnes concernées.</p></LegalSection>
</LegalPage>; }
