import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { legalConfig } from "@/lib/legal/config";

export default function RGPDPage() { return <LegalPage title="Protection des données & RGPD" eyebrow="Vie privée" intro="Cette politique décrit les traitements de données mis en œuvre par NEXORA, leurs finalités, les bases juridiques, les destinataires, les droits des personnes et les mécanismes de protection.">
  <LegalSection title="1. Responsable du traitement"><p>Le responsable du traitement est <strong>{legalConfig.publisherName}</strong>, {legalConfig.legalForm}, dont le siège est situé {legalConfig.address}. Contact général : <strong>{legalConfig.contactEmail}</strong>. Contact relatif aux données personnelles : <strong>{legalConfig.privacyEmail}</strong>. {legalConfig.dpoEmail.startsWith("[") ? "Aucun DPO n’est indiqué comme désigné dans la configuration actuelle." : `Point de contact DPO : ${legalConfig.dpoEmail}.`}</p></LegalSection>
  <LegalSection title="2. Données traitées"><ul className="list-disc space-y-2 pl-5"><li>Compte : adresse e-mail, identifiants techniques, informations de profil et préférences.</li><li>Finance : comptes, soldes, transactions, catégories, budgets, objectifs, prévisions et patrimoine saisis ou importés.</li><li>Open Banking : données de comptes et opérations transmises par le fournisseur d’agrégation après le parcours de connexion.</li><li>IA : questions, réponses, contexte financier strictement nécessaire au traitement demandé, mémoire et traces de gouvernance lorsque la fonctionnalité est activée.</li><li>Technique et sécurité : journaux, informations de session, événements de sécurité et données nécessaires au diagnostic.</li></ul></LegalSection>
  <LegalSection title="3. Finalités et bases juridiques"><ul className="list-disc space-y-2 pl-5"><li><strong>Exécution du service / contrat :</strong> authentification, affichage des données, budget, transactions, prévisions et fonctionnalités demandées.</li><li><strong>Intérêt légitime :</strong> sécurité, prévention des abus, journalisation de sécurité, amélioration technique et continuité du service, avec mise en balance des intérêts.</li><li><strong>Obligation légale :</strong> conservation comptable, fiscale, lutte contre la fraude ou autres obligations lorsqu’elles sont applicables.</li><li><strong>Consentement :</strong> traceurs optionnels et tout traitement qui exige légalement un consentement préalable.</li></ul></LegalSection>
  <LegalSection title="4. Données bancaires et Open Banking"><p>La connexion bancaire passe par le parcours du fournisseur d’agrégation. NEXORA n’a pas vocation à demander ou stocker les identifiants bancaires lorsque l’authentification est réalisée chez le fournisseur ou la banque. Les données reçues sont limitées aux comptes et opérations nécessaires aux fonctionnalités choisies. Une connexion peut être révoquée ; la révocation arrête les synchronisations futures sans entraîner automatiquement l’effacement de l’historique lorsqu’une conservation reste légitime.</p></LegalSection>
  <LegalSection title="5. Intelligence artificielle et automatisation"><p>LIA peut utiliser des données financières autorisées pour produire des analyses, explications, prévisions, recommandations et plans d’action. Les réponses sont assistées par des traitements déterministes et, lorsque configuré, par des modèles d’IA. NEXORA distingue observation, estimation, recommandation et action. Une action financière sensible doit rester soumise aux contrôles de gouvernance et à une validation humaine lorsque le niveau de risque l’exige. Les sorties de l’IA ne constituent pas un conseil professionnel garanti.</p></LegalSection>
  <LegalSection title="6. Destinataires et sous-traitants"><p>Selon les fonctionnalités utilisées, les données peuvent être traitées par les prestataires nécessaires à l’hébergement, la base de données, l’authentification, l’agrégation bancaire, l’envoi de communications, la recherche ou l’IA. Chaque sous-traitant doit être encadré conformément à l’article 28 du RGPD et les garanties de sécurité et de transfert doivent être documentées. La liste opérationnelle des prestataires doit être maintenue à jour avec leur rôle, leur localisation et les garanties applicables.</p></LegalSection>
  <LegalSection title="7. Transferts hors EEE"><p>Lorsqu’un prestataire implique un transfert de données hors Espace économique européen, NEXORA doit appliquer le mécanisme de transfert approprié prévu par le RGPD, notamment une décision d’adéquation lorsqu’elle existe ou des garanties appropriées telles que des clauses contractuelles types, ainsi que les mesures complémentaires nécessaires.</p></LegalSection>
  <LegalSection title="8. Durées de conservation"><div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left"><thead><tr className="border-b"><th className="p-3 font-semibold">Catégorie</th><th className="p-3 font-semibold">Principe de conservation</th></tr></thead><tbody><tr className="border-b"><td className="p-3">Compte et profil</td><td className="p-3">Pendant la durée du compte, puis suppression ou anonymisation selon les obligations applicables.</td></tr><tr className="border-b"><td className="p-3">Données bancaires / transactions</td><td className="p-3">Pendant la fourniture du service et la durée nécessaire à la continuité, à la sécurité et aux obligations légales ; suppression ou anonymisation ensuite.</td></tr><tr className="border-b"><td className="p-3">Journaux de sécurité</td><td className="p-3">Durée limitée au besoin de sécurité, de détection et d’investigation des incidents.</td></tr><tr className="border-b"><td className="p-3">Demandes de droits / support</td><td className="p-3">Le temps nécessaire au traitement puis pendant la durée utile à la preuve et aux obligations légales.</td></tr><tr><td className="p-3">Choix cookies</td><td className="p-3">6 mois dans le mécanisme de préférence actuel, sauf nécessité légale ou technique différente.</td></tr></tbody></table></div><p className="mt-3">Les durées précises sont réévaluées selon la finalité, la minimisation et les obligations de conservation.</p></LegalSection>
  <LegalSection title="9. Vos droits"><p>Vous pouvez, dans les conditions prévues par le RGPD, demander l’accès, la rectification, l’effacement, la limitation du traitement, vous opposer à certains traitements, demander la portabilité lorsque celle-ci est applicable et retirer un consentement. Les demandes sont adressées à <strong>{legalConfig.privacyEmail}</strong>. Une réclamation peut également être adressée à la CNIL, 3 place de Fontenoy, TSA 80751, 75334 Paris Cedex 07.</p></LegalSection>
  <LegalSection title="10. Sécurité"><p>NEXORA applique une approche de sécurité par conception : contrôle d’accès, séparation des utilisateurs, validation serveur des actions sensibles, limitation des permissions, protection des secrets, traçabilité et contrôles de gouvernance. Les mesures sont adaptées au risque et réévaluées lorsque l’architecture ou les traitements évoluent.</p></LegalSection>
  <LegalSection title="11. Violation de données"><p>Tout incident susceptible d’affecter des données personnelles doit être évalué selon une procédure interne. Lorsque les conditions du RGPD sont réunies, la notification à l’autorité compétente et, lorsque nécessaire, l’information des personnes concernées sont effectuées dans les délais prévus par la réglementation.</p></LegalSection>
  <LegalSection title="12. Mineurs"><p>NEXORA n’est pas conçu pour solliciter volontairement des données financières de mineurs. Les conditions d’accès et les mécanismes de consentement parental applicables doivent être respectés lorsque la réglementation l’exige.</p></LegalSection>
  <LegalSection title="13. Mise à jour"><p>Cette politique est mise à jour lorsque les traitements, prestataires, fonctionnalités ou exigences réglementaires évoluent. La date de dernière mise à jour est affichée en bas de page.</p></LegalSection>
</LegalPage>; }
